# Generated by Django 4.2.20 on 2026-03-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_solicitudcambioemail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitudcambioemail',
            new_name='users_solic_user_id_8f3fb4_idx',
            old_name='users_solic_user_id_confirmado_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudcambioemail',
            new_name='users_solic_creado_6858a6_idx',
            old_name='users_solic_creado_idx',
        ),
    ]
