# Generated by Django 4.2.20 on 2026-04-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDinamicoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('codigo', models.CharField(db_index=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('seleccion', 'Seleccion'), ('email', 'Email'), ('telefono', 'Telefono'), ('dni', 'DNI'), ('archivo', 'Archivo')], default='texto', max_length=20)),
                ('obligatorio', models.BooleanField(db_index=True, default=False)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('placeholder', models.CharField(blank=True, max_length=120)),
                ('ayuda', models.CharField(blank=True, max_length=255)),
                ('valor_default', models.CharField(blank=True, max_length=255)),
                ('longitud_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_dinamicos', to='tramites.tipotramite')),
            ],
            options={
                'verbose_name': 'Campo dinamico de tramite',
                'verbose_name_plural': 'Campos dinamicos de tramite',
                'ordering': ['tipo_tramite', 'orden', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampoDinamicoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('valor', models.CharField(max_length=120)),
                ('etiqueta', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='tramites.campodinamicotramite')),
            ],
            options={
                'verbose_name': 'Opcion de campo dinamico',
                'verbose_name_plural': 'Opciones de campo dinamico',
                'ordering': ['campo', 'orden', 'etiqueta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TramiteDatoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('valor', models.JSONField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_cargados', to='tramites.campodinamicotramite')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_dinamicos', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Dato dinamico de tramite',
                'verbose_name_plural': 'Datos dinamicos de tramite',
                'ordering': ['tramite', 'campo__orden', 'id'],
                'indexes': [models.Index(fields=['tramite', 'campo'], name='tramites_tr_tramite_f987f8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tramitedatodinamico',
            constraint=models.UniqueConstraint(fields=('tramite', 'campo'), name='tramites_dato_tramite_campo_uk'),
        ),
        migrations.AddConstraint(
            model_name='campodinamicotramite',
            constraint=models.UniqueConstraint(fields=('tipo_tramite', 'codigo'), name='tramites_campo_tipo_codigo_uk'),
        ),
        migrations.AddConstraint(
            model_name='campodinamicoopcion',
            constraint=models.UniqueConstraint(fields=('campo', 'valor'), name='tramites_campo_opcion_valor_uk'),
        ),
    ]
