# Generated by Django 4.2.20 on 2026-04-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reclamos', '0002_campodinamicoreclamo_campodinamicoopcion_and_more'),
        ('tramites', '0002_campodinamicotramite_campodinamicoopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitotramite',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='requisitotramite',
            name='campo_dinamico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_relacionados', to='tramites.campodinamicotramite'),
        ),
        migrations.CreateModel(
            name='EstadoTramiteTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('requiere_comentario', models.BooleanField(default=False)),
                ('requiere_asignado', models.BooleanField(default=False)),
                ('requiere_area_responsable', models.BooleanField(default=False)),
                ('estado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrada', to='tramites.estadotramite')),
                ('estado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salida', to='tramites.estadotramite')),
                ('areas_permitidas', models.ManyToManyField(blank=True, related_name='transiciones_estado_tramite', to='reclamos.area')),
                ('grupos_permitidos', models.ManyToManyField(blank=True, related_name='transiciones_estado_tramite', to='auth.group')),
            ],
            options={
                'verbose_name': 'Transicion de estado de tramite',
                'verbose_name_plural': 'Transiciones de estado de tramite',
                'ordering': ['estado_origen', 'orden', 'id'],
                'indexes': [models.Index(fields=['estado_origen', 'activo'], name='tramites_es_estado__8ad99b_idx'), models.Index(fields=['estado_destino', 'activo'], name='tramites_es_estado__aa631c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='estadotramitetransicion',
            constraint=models.UniqueConstraint(fields=('estado_origen', 'estado_destino'), name='tramites_estado_transicion_origen_destino_uk'),
        ),
    ]
