# Generated by Django 4.2.20 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tramites", "0003_requisito_runtime_y_transiciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipotramite",
            name="destacado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="tipotramite",
            name="imagen_portada",
            field=models.ImageField(blank=True, null=True, upload_to="tramites/tipos/portadas/%Y/%m/"),
        ),
    ]
