# Generated by Django 4.2.20 on 2025-10-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipio',
                'ordering': ['id'],
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidad',
                'unique_together': {('nombre', 'municipio')},
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('DTC', 'Dispositivo Territorial Comunitario'), ('CAAC', 'Casa de Atención y Acompañamiento Comunitario'), ('CCC', 'Casa Comunitaria Convivencial'), ('CAI', 'Centro de Asistencia Inmediata'), ('IC', 'Institución Conveniada'), ('CT', 'Comunidad Terapéutica'), ('PREVENCION', 'Prevención'), ('ASISTENCIA', 'Asistencia'), ('MIXTA', 'Prevención y Asistencia')], max_length=15)),
                ('nombre', models.CharField(max_length=180)),
                ('direccion', models.CharField(blank=True, max_length=240)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_registro', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('REVISION', 'En Revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=15)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_personeria', models.CharField(blank=True, choices=[('ASOCIACION_CIVIL', 'Asociación Civil'), ('FUNDACION', 'Fundación'), ('SOCIEDAD_CIVIL', 'Sociedad Civil'), ('SOCIEDAD_COMERCIAL', 'Sociedad Comercial'), ('ENTIDAD_PUBLICA', 'Entidad Pública'), ('OTRO', 'Otro')], max_length=20)),
                ('nro_personeria', models.CharField(blank=True, max_length=80)),
                ('fecha_personeria', models.DateField(blank=True, null=True)),
                ('cuit', models.CharField(blank=True, max_length=15)),
                ('nro_registro', models.CharField(blank=True, max_length=80)),
                ('resolucion', models.CharField(blank=True, max_length=120)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('presta_asistencia', models.BooleanField(default=False, verbose_name='Presta servicios de asistencia')),
                ('convenio_obras_sociales', models.BooleanField(default=False, verbose_name='Tiene convenio con Obras Sociales')),
                ('nro_sss', models.CharField(blank=True, max_length=80, verbose_name='Número SSS')),
                ('encargados', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'EncargadoInstitucion'}, related_name='instituciones_encargadas', to=settings.AUTH_USER_MODEL, verbose_name='Encargados de la Institución')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provincia')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PERSONERIA_JURIDICA', 'Personería Jurídica'), ('ESTATUTO', 'Estatuto'), ('ACTA_ASAMBLEA', 'Acta última Asamblea'), ('CONTRATO_SOCIETARIO', 'Contrato Societario'), ('ACTA_CONSTITUCION', 'Acta de Constitución'), ('HABILITACION_MUNICIPAL', 'Habilitación Municipal'), ('PLANOS', 'Planos'), ('CONSTANCIA_AFIP', 'Constancia AFIP'), ('TITULO_PROPIEDAD', 'Título de Propiedad/Contrato'), ('REGLAMENTO_INTERNO', 'Reglamento Interno'), ('SEGUROS', 'Seguros de Responsabilidad Civil'), ('BALANCE', 'Último Balance'), ('MATRICULACION', 'Matriculación Directivos'), ('RECURSOS_HUMANOS', 'Listado Recursos Humanos'), ('PROGRAMAS', 'Programas Preventivos/Asistenciales'), ('ORGANIGRAMA', 'Organigrama'), ('REGISTRO_BIEN_PUBLICO', 'Registro Entidad Bien Público'), ('CONSTANCIA_SSS', 'Constancia SSS'), ('HABILITACION_SANITARIA', 'Habilitación Sanitaria'), ('CONVENIO_EMERGENCIA', 'Convenio Centro Emergencia'), ('CONVENIO_SANITARIO', 'Convenio Centro Sanitario')], max_length=30)),
                ('archivo', models.FileField(blank=True, upload_to='documentos_instituciones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADO', 'Cargado'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.institucion')),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
            },
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['tipo', 'activo'], name='core_instit_tipo_c57e79_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['provincia', 'municipio'], name='core_instit_provinc_d65950_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['nombre'], name='core_instit_nombre_d745e7_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['estado_registro'], name='core_instit_estado__ebdf98_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['nro_registro'], name='core_instit_nro_reg_69ec3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institucion',
            unique_together={('nombre', 'municipio', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['institucion', 'estado'], name='core_docume_institu_9d14e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['tipo', 'obligatorio'], name='core_docume_tipo_fafe81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentorequerido',
            unique_together={('institucion', 'tipo')},
        ),
    ]
