# Generated by Django 4.2.20 on 2026-02-19 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('legajos', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaplanintervencion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.planintervencion'),
        ),
        migrations.AddField(
            model_name='auditoriaplanintervencion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditorialegajo',
            name='legajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.legajoatencion'),
        ),
        migrations.AddField(
            model_name='auditorialegajo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriainstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.institucion'),
        ),
        migrations.AddField(
            model_name='auditoriainstitucion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaeventocritico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.eventocritico'),
        ),
        migrations.AddField(
            model_name='auditoriaeventocritico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.evaluacioninicial'),
        ),
        migrations.AddField(
            model_name='auditoriaevaluacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaderivacion',
            name='derivacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.derivacion'),
        ),
        migrations.AddField(
            model_name='auditoriaderivacion',
            name='institucion_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_derivacion_destino', to='core.institucion'),
        ),
        migrations.AddField(
            model_name='auditoriaderivacion',
            name='institucion_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_derivacion_origen', to='core.institucion'),
        ),
        migrations.AddField(
            model_name='auditoriaderivacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaconsentimiento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que aprobó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaconsentimiento',
            name='consentimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='legajos.consentimiento'),
        ),
        migrations.AddField(
            model_name='auditoriaconsentimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaciudadano',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='legajos.ciudadano'),
        ),
        migrations.AddField(
            model_name='auditoriaciudadano',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosensible',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosensible',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertaauditoria',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertaauditoria',
            name='usuario_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sesionusuario',
            index=models.Index(fields=['usuario', '-inicio_sesion'], name='core_sesion_usuario_a37284_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionusuario',
            index=models.Index(fields=['activa', '-ultima_actividad'], name='core_sesion_activa_28a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionmasiva',
            index=models.Index(fields=['usuario', '-fecha_inicio'], name='core_operac_usuario_164b62_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionmasiva',
            index=models.Index(fields=['tipo', '-fecha_inicio'], name='core_operac_tipo_943dee_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionmasiva',
            index=models.Index(fields=['modelo_afectado', '-fecha_inicio'], name='core_operac_modelo__5bee6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('nombre', 'provincia')},
        ),
        migrations.AddIndex(
            model_name='logdescargaarchivo',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_logdes_usuario_e35018_idx'),
        ),
        migrations.AddIndex(
            model_name='logdescargaarchivo',
            index=models.Index(fields=['archivo_nombre'], name='core_logdes_archivo_2cba0f_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccion',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_logacc_usuario_c8c3be_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccion',
            index=models.Index(fields=['accion', '-timestamp'], name='core_logacc_accion_2ca565_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccion',
            index=models.Index(fields=['modelo', '-timestamp'], name='core_logacc_modelo_336932_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('nombre', 'municipio')},
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['tipo', 'activo'], name='core_instit_tipo_c57e79_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['provincia', 'municipio'], name='core_instit_provinc_d65950_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['nombre'], name='core_instit_nombre_d745e7_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['estado_registro'], name='core_instit_estado__ebdf98_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['nro_registro'], name='core_instit_nro_reg_69ec3a_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['activo', 'tipo', 'provincia'], name='core_instit_activo_f386b5_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['estado_registro', 'tipo'], name='core_instit_estado__cde004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institucion',
            unique_together={('nombre', 'municipio', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['institucion', 'estado'], name='core_docume_institu_9d14e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['tipo', 'obligatorio'], name='core_docume_tipo_fafe81_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['estado', 'obligatorio'], name='core_docume_estado_527464_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentorequerido',
            unique_together={('institucion', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='auditoriaplanintervencion',
            index=models.Index(fields=['plan', '-timestamp'], name='core_audito_plan_id_e612cd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaplanintervencion',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_a2d1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaplanintervencion',
            index=models.Index(fields=['cambio_vigencia', '-timestamp'], name='core_audito_cambio__2e434f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['legajo', '-timestamp'], name='core_audito_legajo__fddf11_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_92821a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['accion', '-timestamp'], name='core_audito_accion_6a8cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['cambio_estado', '-timestamp'], name='core_audito_cambio__c69a79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['cambio_responsable', '-timestamp'], name='core_audito_cambio__d4797a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialegajo',
            index=models.Index(fields=['cambio_nivel_riesgo', '-timestamp'], name='core_audito_cambio__7a45f7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucion',
            index=models.Index(fields=['institucion', '-timestamp'], name='core_audito_institu_4dae0f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucion',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_1f1fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucion',
            index=models.Index(fields=['cambio_estado_registro', '-timestamp'], name='core_audito_cambio__d3d218_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainstitucion',
            index=models.Index(fields=['cambio_activo', '-timestamp'], name='core_audito_cambio__2fb2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaeventocritico',
            index=models.Index(fields=['evento', '-timestamp'], name='core_audito_evento__339832_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaeventocritico',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_bbe5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaeventocritico',
            index=models.Index(fields=['tipo_evento', '-timestamp'], name='core_audito_tipo_ev_05e307_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevaluacion',
            index=models.Index(fields=['evaluacion', '-timestamp'], name='core_audito_evaluac_062f30_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevaluacion',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_41935b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevaluacion',
            index=models.Index(fields=['genera_alerta', '-timestamp'], name='core_audito_genera__54b1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevaluacion',
            index=models.Index(fields=['cambio_riesgo_suicida', '-timestamp'], name='core_audito_cambio__a7eb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevaluacion',
            index=models.Index(fields=['cambio_violencia', '-timestamp'], name='core_audito_cambio__e1e1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaderivacion',
            index=models.Index(fields=['derivacion', '-timestamp'], name='core_audito_derivac_64a427_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaderivacion',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_a42a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaderivacion',
            index=models.Index(fields=['cambio_estado', '-timestamp'], name='core_audito_cambio__c7360d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaderivacion',
            index=models.Index(fields=['institucion_origen', '-timestamp'], name='core_audito_institu_978c78_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaderivacion',
            index=models.Index(fields=['institucion_destino', '-timestamp'], name='core_audito_institu_155d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaconsentimiento',
            index=models.Index(fields=['consentimiento', '-timestamp'], name='core_audito_consent_54ecf7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaconsentimiento',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_2a00d6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaconsentimiento',
            index=models.Index(fields=['accion', '-timestamp'], name='core_audito_accion_6a18ef_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaciudadano',
            index=models.Index(fields=['ciudadano', '-timestamp'], name='core_audito_ciudada_bb299d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaciudadano',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_0bcb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaciudadano',
            index=models.Index(fields=['accion', '-timestamp'], name='core_audito_accion_09497b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaciudadano',
            index=models.Index(fields=['modifico_datos_personales', '-timestamp'], name='core_audito_modific_a712d3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosensible',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='core_audito_content_02bba0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosensible',
            index=models.Index(fields=['usuario', '-timestamp'], name='core_audito_usuario_fc1fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosensible',
            index=models.Index(fields=['tipo_acceso', '-timestamp'], name='core_audito_tipo_ac_68dd73_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosensible',
            index=models.Index(fields=['fuera_horario', '-timestamp'], name='core_audito_fuera_h_59f987_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosensible',
            index=models.Index(fields=['acceso_multiple', '-timestamp'], name='core_audito_acceso__d596f6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaauditoria',
            index=models.Index(fields=['usuario_afectado', '-timestamp'], name='core_alerta_usuario_f9659a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaauditoria',
            index=models.Index(fields=['tipo', 'severidad'], name='core_alerta_tipo_143593_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaauditoria',
            index=models.Index(fields=['revisada', '-timestamp'], name='core_alerta_revisad_6fcfbc_idx'),
        ),
    ]
