# Generated by Django 4.2.20 on 2025-10-31 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('inicio_sesion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fin_sesion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-inicio_sesion'],
                'indexes': [models.Index(fields=['usuario', '-inicio_sesion'], name='core_sesion_usuario_a37284_idx'), models.Index(fields=['activa', '-ultima_actividad'], name='core_sesion_activa_28a6a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogDescargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_path', models.CharField(max_length=500)),
                ('modelo_origen', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Descarga',
                'verbose_name_plural': 'Logs de Descargas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='core_logdes_usuario_e35018_idx'), models.Index(fields=['archivo_nombre'], name='core_logdes_archivo_2cba0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('DOWNLOAD', 'Descargar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('objeto_repr', models.CharField(blank=True, max_length=200)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='core_logacc_usuario_c8c3be_idx'), models.Index(fields=['accion', '-timestamp'], name='core_logacc_accion_2ca565_idx'), models.Index(fields=['modelo', '-timestamp'], name='core_logacc_modelo_336932_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTIPLES_LOGINS', 'Múltiples inicios de sesión'), ('ACTIVIDAD_SOSPECHOSA', 'Actividad sospechosa'), ('DESCARGA_MASIVA', 'Descarga masiva de archivos'), ('ACCESO_FUERA_HORARIO', 'Acceso fuera de horario'), ('CAMBIOS_CRITICOS', 'Cambios en datos críticos')], max_length=30)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('descripcion', models.TextField()),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Auditoría',
                'verbose_name_plural': 'Alertas de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario_afectado', '-timestamp'], name='core_alerta_usuario_f9659a_idx'), models.Index(fields=['tipo', 'severidad'], name='core_alerta_tipo_143593_idx'), models.Index(fields=['revisada', '-timestamp'], name='core_alerta_revisad_6fcfbc_idx')],
            },
        ),
    ]
