# Generated by Django 4.2.20 on 2025-11-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_performance_indexes'),
        ('core', '0002_sesionusuario_logdescargaarchivo_logaccion_and_more'),
    ]

    operations = [
    ]
