# Generated by Django 4.2.20 on 2025-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20251104_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='estado_registro',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('REVISION', 'En Revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(db_index=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(choices=[('DTC', 'Dispositivo Territorial Comunitario'), ('CAAC', 'Casa de Atención y Acompañamiento Comunitario'), ('CCC', 'Casa Comunitaria Convivencial'), ('CAI', 'Centro de Asistencia Inmediata'), ('IC', 'Institución Conveniada'), ('CT', 'Comunidad Terapéutica')], db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='documentorequerido',
            index=models.Index(fields=['estado', 'obligatorio'], name='core_docume_estado_527464_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['activo', 'tipo', 'provincia'], name='core_instit_activo_f386b5_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['estado_registro', 'tipo'], name='core_instit_estado__cde004_idx'),
        ),
    ]
