# Generated by Django 4.2.20 on 2025-11-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0014_remove_derivacion_origen'),
        ('core', '0005_operacionmasiva_auditoriaplanintervencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaciudadano',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='legajos.ciudadano'),
        ),
    ]
