-- Esquema Relevamientos (mobile)
-- Ejecutar en SQL Editor de Supabase.

create extension if not exists pgcrypto;

-- =========================================
-- 1) Catalogo instituciones
-- =========================================
create table if not exists public.instituciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  estado text not null default 'ACTIVA',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ID hardcodeado 1 (pedido actual)
insert into public.instituciones (id, nombre, estado)
values (1, 'Institucion Demo', 'ACTIVA')
on conflict (id) do nothing;

-- =========================================
-- 2) Relevamientos (formulario principal)
-- =========================================
create table if not exists public.relevamientos (
  id uuid primary key default gen_random_uuid(),

  -- Para idempotencia desde mobile (offline -> sync)
  client_uid uuid not null unique default gen_random_uuid(),

  -- Relacion requerida
  id_institucion bigint not null default 1 references public.instituciones(id),

  -- Datos responsable (opcionales)
  responsable_nombre text,
  responsable_apellido text,
  responsable_dni text,
  responsable_telefono text,
  responsable_email text,
  responsable_funcion text,
  usuario_username text,

  -- Paso 2: institucion
  tiene_colaboradores text check (tiene_colaboradores in ('Si', 'No')) default 'No',
  cantidad_colaboradores integer,
  tipo_espacio_fisico text default 'Espacio Propio',
  espacio_fisico_otro text,
  tiene_cocina text check (tiene_cocina in ('Si', 'No')) default 'No',

  espacio_elaboracion_alimentos text check (espacio_elaboracion_alimentos in ('Si', 'No')) default 'No',
  almacenamiento_alimentos_secos text check (almacenamiento_alimentos_secos in ('Si', 'No')) default 'No',
  heladera text check (heladera in ('Si', 'No')) default 'No',
  freezer text check (freezer in ('Si', 'No')) default 'No',
  recipiente_residuos_organicos text check (recipiente_residuos_organicos in ('Si', 'No')) default 'No',
  recipiente_residuos_reciclables text check (recipiente_residuos_reciclables in ('Si', 'No')) default 'No',
  otros_residuos text check (otros_residuos in ('Si', 'No')) default 'No',
  recipiente_otros_residuos text check (recipiente_otros_residuos in ('Si', 'No')) default 'No',
  abastecimiento_combustible text default 'Gas natural',
  abastecimiento_agua text default 'Agua de red',
  abastecimiento_agua_otro text,
  instalacion_electrica text check (instalacion_electrica in ('Si', 'No')) default 'No',

  espacio_equipado text check (espacio_equipado in ('Si', 'No')) default 'No',
  tiene_ventilacion text check (tiene_ventilacion in ('Si', 'No')) default 'No',
  tiene_salida_emergencia text check (tiene_salida_emergencia in ('Si', 'No')) default 'No',
  salida_emergencia_senializada text check (salida_emergencia_senializada in ('Si', 'No')) default 'No',
  tiene_equipacion_incendio text check (tiene_equipacion_incendio in ('Si', 'No')) default 'No',
  tiene_botiquin text check (tiene_botiquin in ('Si', 'No')) default 'No',
  tiene_buena_iluminacion text check (tiene_buena_iluminacion in ('Si', 'No')) default 'No',
  tiene_sanitarios text check (tiene_sanitarios in ('Si', 'No')) default 'No',
  desague_hinodoro text default 'Cloaca',
  gestion_quejas text default 'Buzon',
  gestion_quejas_otro text,
  informacion_quejas text check (informacion_quejas in ('Si', 'No')) default 'No',
  frecuencia_limpieza text default '1 vez por dia',

  -- Anexo
  tipo_insumo text default 'Dinero',
  frecuencia_insumo text default '1 vez por semana',
  tecnologia text default 'Computadora',
  acceso_institucion text default 'Calle de tierra',
  distancia_transporte text default 'De 0 a 5 cuadras',
  servicio_internet text check (servicio_internet in ('Si', 'No')) default 'No',
  zona_inundable text check (zona_inundable in ('Si', 'No')) default 'No',

  actividades_jardin_maternal text check (actividades_jardin_maternal in ('Si', 'No')) default 'No',
  actividades_jardin_infantes text check (actividades_jardin_infantes in ('Si', 'No')) default 'No',
  apoyo_escolar text check (apoyo_escolar in ('Si', 'No')) default 'No',
  alfabetizacion_terminalidad text check (alfabetizacion_terminalidad in ('Si', 'No')) default 'No',
  capacitaciones_talleres text check (capacitaciones_talleres in ('Si', 'No')) default 'No',
  tipo_talleres text,
  promocion_salud text check (promocion_salud in ('Si', 'No')) default 'No',
  actividades_discapacidad text check (actividades_discapacidad in ('Si', 'No')) default 'No',
  actividades_recreativas text check (actividades_recreativas in ('Si', 'No')) default 'No',
  cuales_actividades_recreativas text,
  actividades_culturales text check (actividades_culturales in ('Si', 'No')) default 'No',
  cuales_actividades_culturales text,
  emprendimientos_productivos text check (emprendimientos_productivos in ('Si', 'No')) default 'No',
  cuales_emprendimientos_productivos text,
  actividades_religiosas text check (actividades_religiosas in ('Si', 'No')) default 'No',
  actividades_huerta text check (actividades_huerta in ('Si', 'No')) default 'No',
  otras_actividades text check (otras_actividades in ('Si', 'No')) default 'No',
  cuales_otras_actividades text,

  -- Paso 4: geolocalizacion
  latitud numeric(10, 7),
  longitud numeric(10, 7),

  -- Paso 6
  observaciones text,

  -- Firma vectorial (paths) y/o imagen
  firma_paths jsonb not null default '[]'::jsonb,
  firma_storage_path text,

  -- Fecha/hora real del relevamiento en campo
  relevado_at timestamptz not null default now(),

  -- Estado sync (visible en app)
  sync_estado text not null default 'SINCRONIZADO'
    check (sync_estado in ('PENDIENTE', 'SINCRONIZANDO', 'SINCRONIZADO', 'ERROR')),
  sync_error text,
  last_synced_at timestamptz,

  -- Auditoria clasica
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),

  -- Opcional para borrado logico
  deleted_at timestamptz
);

create index if not exists idx_relevamientos_institucion on public.relevamientos(id_institucion);
create index if not exists idx_relevamientos_created_at on public.relevamientos(created_at desc);
create index if not exists idx_relevamientos_relevado_at on public.relevamientos(relevado_at desc);
create index if not exists idx_relevamientos_sync_estado on public.relevamientos(sync_estado);
create index if not exists idx_relevamientos_created_by on public.relevamientos(created_by);
alter table public.relevamientos add column if not exists usuario_username text;
alter table public.relevamientos add column if not exists relevado_at timestamptz;
update public.relevamientos
set relevado_at = coalesce(relevado_at, created_at, last_synced_at, now())
where relevado_at is null;
alter table public.relevamientos alter column relevado_at set default now();

-- =========================================
-- 3) Campos extras (paso 6)
-- =========================================
create table if not exists public.relevamiento_campos_extra (
  id bigserial primary key,
  relevamiento_id uuid not null references public.relevamientos(id) on delete cascade,
  orden integer not null default 1,
  nombre text not null,
  valor text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_campos_extra_relevamiento on public.relevamiento_campos_extra(relevamiento_id);

-- =========================================
-- 4) Adjuntos (fotos/documentos/firma)
-- =========================================
create table if not exists public.relevamiento_adjuntos (
  id uuid primary key default gen_random_uuid(),
  relevamiento_id uuid not null references public.relevamientos(id) on delete cascade,
  categoria text not null check (categoria in ('EVIDENCIA', 'DOCUMENTO', 'FIRMA')),
  tipo_archivo text not null check (tipo_archivo in ('IMAGEN', 'ARCHIVO')),
  storage_bucket text not null default 'relevamientos',
  storage_path text not null,
  nombre_original text,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create index if not exists idx_adjuntos_relevamiento on public.relevamiento_adjuntos(relevamiento_id);
create index if not exists idx_adjuntos_bucket_path on public.relevamiento_adjuntos(storage_bucket, storage_path);

-- =========================================
-- 5) Triggers auditoria (updated_at + user)
-- =========================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function public.set_audit_user()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    if new.created_by is null then
      new.created_by = auth.uid();
    end if;
    if new.updated_by is null then
      new.updated_by = auth.uid();
    end if;
  else
    new.updated_by = auth.uid();
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists instituciones_set_updated_at on public.instituciones;
create trigger instituciones_set_updated_at
before update on public.instituciones
for each row execute function public.set_updated_at();

drop trigger if exists relevamientos_set_updated_at on public.relevamientos;
create trigger relevamientos_set_updated_at
before update on public.relevamientos
for each row execute function public.set_updated_at();

drop trigger if exists relevamientos_set_audit_user on public.relevamientos;
create trigger relevamientos_set_audit_user
before insert or update on public.relevamientos
for each row execute function public.set_audit_user();

drop trigger if exists campos_extra_set_updated_at on public.relevamiento_campos_extra;
create trigger campos_extra_set_updated_at
before update on public.relevamiento_campos_extra
for each row execute function public.set_updated_at();

-- =========================================
-- 6) RLS (base para desarrollo)
-- =========================================
alter table public.instituciones enable row level security;
alter table public.relevamientos enable row level security;
alter table public.relevamiento_campos_extra enable row level security;
alter table public.relevamiento_adjuntos enable row level security;

drop policy if exists instituciones_all_dev on public.instituciones;
create policy instituciones_all_dev on public.instituciones
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists relevamientos_all_dev on public.relevamientos;
create policy relevamientos_all_dev on public.relevamientos
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists campos_extra_all_dev on public.relevamiento_campos_extra;
create policy campos_extra_all_dev on public.relevamiento_campos_extra
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists adjuntos_all_dev on public.relevamiento_adjuntos;
create policy adjuntos_all_dev on public.relevamiento_adjuntos
for all to anon, authenticated
using (true)
with check (true);

-- =========================================
-- 7) Storage bucket + policies
-- =========================================
insert into storage.buckets (id, name, public)
values ('relevamientos', 'relevamientos', false)
on conflict (id) do nothing;

drop policy if exists relevamientos_storage_select on storage.objects;
create policy relevamientos_storage_select on storage.objects
for select to anon, authenticated
using (bucket_id = 'relevamientos');

drop policy if exists relevamientos_storage_insert on storage.objects;
create policy relevamientos_storage_insert on storage.objects
for insert to anon, authenticated
with check (bucket_id = 'relevamientos');

drop policy if exists relevamientos_storage_update on storage.objects;
create policy relevamientos_storage_update on storage.objects
for update to anon, authenticated
using (bucket_id = 'relevamientos')
with check (bucket_id = 'relevamientos');

drop policy if exists relevamientos_storage_delete on storage.objects;
create policy relevamientos_storage_delete on storage.objects
for delete to anon, authenticated
using (bucket_id = 'relevamientos');
