from .views_ciudadanos import (
    AdmisionPaso1View,
    AdmisionPaso2View,
    AdmisionPaso3View,
    CiudadanoConfirmarView,
    CiudadanoCreateView,
    CiudadanoDetailView,
    CiudadanoListView,
    CiudadanoManualView,
    CiudadanoUpdateView,
    LegajoCreateView,
)
from .views_clinico import (
    CambiarResponsableView,
    CerrarAlertaEventoView,
    DerivacionCreateView,
    DerivacionListView,
    DerivacionUpdateView,
    DispositivoDerivacionesView,
    EvaluacionInicialView,
    EvaluacionListView,
    EventoCriticoCreateView,
    EventoListView,
    EventoUpdateView,
    ExportarCSVView,
    LegajoCerrarView,
    LegajoDetailView,
    LegajoListView,
    LegajoReabrirView,
    PlanIntervencionView,
    PlanListView,
    PlanUpdateView,
    ReportesView,
    SeguimientoCreateView,
    SeguimientoListView,
    SeguimientoUpdateView,
)
from .views_dashboard_contactos import dashboard_contactos, exportar_reporte_contactos, metricas_contactos_api, metricas_red_contactos_api
from .views_historial_contactos import contactos_api, crear_contacto, detalle_contacto, editar_contacto, eliminar_contacto, historial_contactos_view
from .views_operativa import (
    ActividadesInscritoListView,
    InscribirActividadView,
    InstitucionCreateView,
    InstitucionDeleteView,
    InstitucionListView,
    InstitucionUpdateView,
    LegajoInstitucionalCreateView,
    LegajoInstitucionalDetailView,
    LegajoInstitucionalListView,
    LegajoInstitucionalUpdateView,
    actividades_por_institucion,
    marcar_etapa_plan,
)
from .views_red_contactos import (
    buscar_ciudadanos_api,
    buscar_usuarios_api,
    crear_contacto_emergencia,
    crear_profesional,
    crear_vinculo,
    dispositivos_api,
    emergencias_api,
    profesionales_api,
    red_contactos_view,
    vinculos_api,
)
