from django.urls import path

from .views import (
    PortalCiudadanoHomeView,
    PortalCiudadanoChatView,
    PortalCiudadanoLoginView,
    PortalCiudadanoLogoutView,
    PortalCiudadanoMisSolicitudesView,
    PortalCiudadanoMiPerfilView,
    PortalCiudadanoReclamoConfirmarView,
    PortalCiudadanoReclamoDetalleView,
    PortalCiudadanoReclamoDetalleSolicitudView,
    PortalCiudadanoReclamoEnviadoView,
    PortalCiudadanoReclamosView,
    PortalCiudadanoTramiteConfirmarView,
    PortalCiudadanoTramiteDetalleSolicitudView,
    PortalCiudadanoTramiteDetalleView,
    PortalCiudadanoTramiteEnviadoView,
    PortalCiudadanoTramitesView,
    portal_ciudadano_cancelar_turno,
    portal_ciudadano_confirmar_turno,
    portal_ciudadano_mis_programas,
    portal_ciudadano_mis_turnos,
    portal_ciudadano_programa_detalle,
    portal_ciudadano_solicitar_turno,
    portal_ciudadano_turno_calendario,
    portal_ciudadano_turno_confirmado,
    portal_ciudadano_turno_slots,
)

app_name = "portal_ciudadano"

urlpatterns = [
    path("", PortalCiudadanoHomeView.as_view(), name="home"),
    path("chat/", PortalCiudadanoChatView.as_view(), name="chat"),
    path("login/", PortalCiudadanoLoginView.as_view(), name="login"),
    path("logout/", PortalCiudadanoLogoutView.as_view(), name="logout"),
    path("mi-perfil/", PortalCiudadanoMiPerfilView.as_view(), name="mi_perfil"),
    path("mis-solicitudes/", PortalCiudadanoMisSolicitudesView.as_view(), name="mis_solicitudes"),
    path("programas/", portal_ciudadano_mis_programas, name="programas"),
    path("programas/<int:pk>/", portal_ciudadano_programa_detalle, name="programa_detalle"),
    path("turnos/", portal_ciudadano_mis_turnos, name="turnos"),
    path("turnos/solicitar/", portal_ciudadano_solicitar_turno, name="solicitar_turno"),
    path("turnos/solicitar/<int:recurso_id>/calendario/", portal_ciudadano_turno_calendario, name="turno_calendario"),
    path("turnos/solicitar/<int:recurso_id>/slots/", portal_ciudadano_turno_slots, name="turno_slots"),
    path("turnos/solicitar/<int:recurso_id>/confirmar/", portal_ciudadano_confirmar_turno, name="confirmar_turno"),
    path("turnos/<int:pk>/confirmado/", portal_ciudadano_turno_confirmado, name="turno_confirmado"),
    path("turnos/<int:pk>/cancelar/", portal_ciudadano_cancelar_turno, name="cancelar_turno"),
    path("reclamos/", PortalCiudadanoReclamosView.as_view(), name="reclamos"),
    path("reclamos/detalle/", PortalCiudadanoReclamoDetalleView.as_view(), name="reclamos_detalle"),
    path("reclamos/confirmar/", PortalCiudadanoReclamoConfirmarView.as_view(), name="reclamos_confirmar"),
    path("reclamos/enviado/", PortalCiudadanoReclamoEnviadoView.as_view(), name="reclamos_enviado"),
    path(
        "mis-solicitudes/reclamo/<int:pk>/",
        PortalCiudadanoReclamoDetalleSolicitudView.as_view(),
        name="detalle_reclamo",
    ),
    path("tramites/", PortalCiudadanoTramitesView.as_view(), name="tramites"),
    path("tramites/detalle/", PortalCiudadanoTramiteDetalleView.as_view(), name="tramites_detalle"),
    path("tramites/confirmar/", PortalCiudadanoTramiteConfirmarView.as_view(), name="tramites_confirmar"),
    path("tramites/enviado/", PortalCiudadanoTramiteEnviadoView.as_view(), name="tramites_enviado"),
    path(
        "mis-solicitudes/tramite/<int:pk>/",
        PortalCiudadanoTramiteDetalleSolicitudView.as_view(),
        name="detalle_tramite",
    ),
]
