import copy
import os


DEFAULT_BRANDING = {
    "key": "default",
    "application_name": "NODO",
    "favicon_path": "custom/branding/default/favicon.png",
    "sidebar_logo_path": "custom/branding/default/app-logo.png",
    "sidebar_collapsed_logo_path": "custom/branding/default/app-logo.png",
    "login_logo_path": "custom/branding/default/login-logo.svg",
    "login_illustration_path": "custom/branding/default/login-illustration.svg",
    "login_background_image_path": "custom/branding/default/login-background.png",
    "footer_logo_path": "custom/branding/default/footer-logo.png",
    "chatbot_bubble": {
        "size": "56px",
        "background": "var(--nodo-gradient)",
        "hover_background": "var(--nodo-purple)",
        "icon_size": "1.25rem",
        "icon_color": "#FFFFFF",
    },
    "chatbot_window": {
        "header_background": "var(--nodo-gradient)",
        "submit_background": "var(--nodo-gradient)",
        "submit_hover_background": "var(--nodo-purple)",
        "input_focus_ring": "var(--color-primario)",
        "title": "Asistente Virtual",
        "welcome_message": "¡Hola! Soy tu asistente virtual. ¿En que puedo ayudarte?",
    },
    "citizen_list": {
        "action_view_color": "#3B82F6",
        "action_view_hover_bg": "#EFF6FF",
    },
    "portal": {
        "title": "Portal NODO",
        "subtitle": "Registro de Instituciones",
        "contact_email": "info@nodo.gob.ar",
        "logo_path": "",
        "logo_width": "56px",
        "logo_height": "56px",
        "background_color": "#FFFFFF",
        "icon_bg": "linear-gradient(135deg, #3B82F6 0%, #8B5CF6 100%)",
        "icon_name": "fa-network-wired",
        "footer_title": "NODO",
        "header_contact_icon_bg": "#F9FAFB",
        "header_contact_icon_border": "#E5E7EB",
        "header_contact_icon_color": "#3B82F6",
        "page_header_icon_mode": "solid",
        "page_header_icon_color": "#2563EB",
        "page_header_icon_gradient_start": "#3B82F6",
        "page_header_icon_gradient_end": "#8B5CF6",
        "primary_button_gradient_start": "#3B82F6",
        "primary_button_gradient_end": "#8B5CF6",
        "primary_button_hover_start": "#2563EB",
        "primary_button_hover_end": "#7C3AED",
        "secondary_button_bg": "#D1D5DB",
        "secondary_button_hover_bg": "#9CA3AF",
        "secondary_button_text": "#1F2937",
        "secondary_button_border": "#D1D5DB",
        "floating_help_bg": "#9333EA",
        "floating_help_hover_bg": "#7E22CE",
        "floating_help_icon_color": "#FFFFFF",
        "stats_icon_1_bg": "#1E3A8A",
        "stats_icon_2_bg": "#15803D",
        "stats_icon_3_bg": "#EA580C",
        "stats_icon_4_bg": "#6D28D9",
        "stats_system_icon_color": "#1E3A8A",
        "stats_progress_1": "#16A34A",
        "stats_progress_2": "#2563EB",
        "stats_progress_3": "#7C3AED",
        "home": {
            "status_badge_bg": "#F0F9FF",
            "status_badge_border": "#BAE6FD",
            "status_badge_text": "#0369A1",
            "status_badge_dot": "#10B981",
            "primary_icon_mode": "badge",
            "primary_icon_gradient_start": "#3B82F6",
            "primary_icon_gradient_end": "#8B5CF6",
            "primary_button_gradient_start": "#3B82F6",
            "primary_button_gradient_end": "#8B5CF6",
            "primary_button_hover_start": "#2563EB",
            "primary_button_hover_end": "#7C3AED",
            "secondary_icon_mode": "badge",
            "secondary_icon_gradient_start": "#10B981",
            "secondary_icon_gradient_end": "#059669",
            "secondary_button_gradient_start": "#10B981",
            "secondary_button_gradient_end": "#059669",
            "secondary_button_hover_start": "#059669",
            "secondary_button_hover_end": "#047857",
            "tertiary_icon_mode": "badge",
            "tertiary_icon_gradient_start": "#64748B",
            "tertiary_icon_gradient_end": "#475569",
            "tertiary_button_gradient_start": "#64748B",
            "tertiary_button_gradient_end": "#475569",
            "tertiary_button_hover_start": "#475569",
            "tertiary_button_hover_end": "#334155",
            "support_icon_mode": "badge",
            "support_icon_bg": "#F9FAFB",
            "support_icon_border": "#E5E7EB",
            "support_icon_color": "#64748B",
            "support_icon_gradient_start": "#64748B",
            "support_icon_gradient_end": "#475569",
            "support_button_bg": "#64748B",
            "support_button_hover_bg": "#475569",
            "contact_icon_color": "#3B82F6",
            "process_title_icon_bg": "#3B82F6",
            "docs_icon_bg": "#F59E0B",
            "docs_check_bg": "#10B981",
            "steps_icon_bg": "#3B82F6",
            "steps_complete_bg": "#10B981",
            "notice_bg": "#F0F9FF",
            "notice_border": "#BAE6FD",
            "notice_text": "#0369A1",
        },
    },
    "conversations": {
        "list": {
            "metrics_button_bg": "#2563EB",
            "metrics_button_hover_bg": "#1D4ED8",
            "config_button_bg": "#16A34A",
            "config_button_hover_bg": "#15803D",
            "auto_assign_button_bg": "#9333EA",
            "auto_assign_button_hover_bg": "#7E22CE",
            "filter_button_bg": "#2563EB",
            "filter_button_hover_bg": "#1D4ED8",
            "stat_alert_bg": "#FEE2E2",
            "stat_alert_icon": "#DC2626",
            "stat_success_bg": "#DCFCE7",
            "stat_success_icon": "#16A34A",
            "stat_time_bg": "#DBEAFE",
            "stat_time_icon": "#2563EB",
            "action_view_color": "#2563EB",
            "action_view_hover_color": "#1E3A8A",
            "action_reassign_color": "#9333EA",
            "action_reassign_hover_color": "#6B21A8",
            "action_assign_color": "#16A34A",
            "action_assign_hover_color": "#14532D",
        },
        "chat_public": {
            "header_icon_gradient_start": "#3B82F6",
            "header_icon_gradient_end": "#8B5CF6",
            "status_badge_bg": "#F0F9FF",
            "status_badge_border": "#BAE6FD",
            "status_badge_text": "#0369A1",
            "status_badge_dot": "#10B981",
            "secure_icon_bg": "#F9FAFB",
            "secure_icon_border": "#E5E7EB",
            "secure_icon_color": "#3B82F6",
            "anonymous_icon_mode": "badge",
            "anonymous_icon_gradient_start": "#3B82F6",
            "anonymous_icon_gradient_end": "#8B5CF6",
            "personal_icon_mode": "badge",
            "personal_icon_gradient_start": "#10B981",
            "personal_icon_gradient_end": "#059669",
            "primary_button_gradient_start": "#3B82F6",
            "primary_button_gradient_end": "#8B5CF6",
            "primary_button_hover_start": "#2563EB",
            "primary_button_hover_end": "#7C3AED",
            "secondary_button_gradient_start": "#10B981",
            "secondary_button_gradient_end": "#059669",
            "secondary_button_hover_start": "#059669",
            "secondary_button_hover_end": "#047857",
        },
    },
    "citizen_form": {
        "header_icon_mode": "badge",
        "header_icon_bg": "#10B981",
        "header_icon_color": "#FFFFFF",
        "header_icon_gradient_start": "#7928CA",
        "header_icon_gradient_end": "#FF0080",
        "confirm_header_icon_name": "fa-check-circle",
        "confirm_header_icon_mode": "solid",
        "confirm_header_icon_wrapper": "badge",
        "confirm_header_icon_bg": "#DCFCE7",
        "confirm_header_icon_color": "#16A34A",
        "confirm_header_icon_gradient_start": "#7928CA",
        "confirm_header_icon_gradient_end": "#FF0080",
        "confirm_header_icon_size": "1.25rem",
        "confirm_breadcrumb_home_icon_mode": "solid",
        "confirm_breadcrumb_home_icon_color": "#9CA3AF",
        "confirm_breadcrumb_home_icon_gradient_start": "#7928CA",
        "confirm_breadcrumb_home_icon_gradient_end": "#FF0080",
        "confirm_renaper_card_bg": "#F0FDF4",
        "confirm_renaper_card_border": "#BBF7D0",
        "confirm_renaper_card_text": "#15803D",
        "confirm_renaper_card_muted_text": "#16A34A",
        "confirm_renaper_card_info_bg": "#DCFCE7",
        "confirm_renaper_card_info_text": "#15803D",
        "confirm_back_button_class": "btn-nodo btn-secondary btn-base",
        "renaper_header_icon_mode": "badge",
        "renaper_header_icon_wrapper": "badge",
        "renaper_header_icon_bg": "linear-gradient(135deg, #3B82F6 0%, #2563EB 100%)",
        "renaper_header_icon_color": "#FFFFFF",
        "renaper_header_icon_gradient_start": "#7928CA",
        "renaper_header_icon_gradient_end": "#FF0080",
        "renaper_header_icon_size": "1.25rem",
        "cancel_button_class": "px-6 py-3 border border-[#E5E7EB] text-[#4A5565] rounded-lg hover:bg-[#F9FAFB] transition-colors",
        "back_button_class": "text-[#8C8C8C] hover:text-[#4A5565] font-medium transition-colors",
    },
    "program_detail_nachec": {
        "tab_active_border_color": "#3B82F6",
        "tab_active_text_color": "#2563EB",
        "hero_stats": {
            "card_mode": "default_gradient",
            "show_badges": True,
            "card_border": "#D9D9D9",
            "card_shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
            "value_color": "#000000",
            "value_size": "30px",
            "value_weight": "700",
            "label_color": "#000000",
            "label_size": "16px",
            "label_weight": "400",
            "meta_color": "#000000",
            "meta_size": "16px",
            "meta_weight": "400",
            "icon_mode": "default",
            "icon_size": "36px",
            "icon_gradient_start": "#5059BC",
            "icon_gradient_end": "#252956",
        },
        "flow_cycle": {
            "icon_mode": "default",
            "icon_container_bg": "#E5E7EB",
            "icon_container_size": "41px",
            "icon_size": "20px",
            "icon_gradient_start": "#5059BC",
            "icon_gradient_end": "#F26DF9",
        },
        "prestations_status": {
            "mode": "default",
            "delivered_bg": "#F9FAFB",
            "delivered_border": "#A54FA9",
            "delivered_shadow": "-5px 0 0 0 #A54FA9",
            "delivered_text": "#A54FA9",
            "scheduled_bg": "#F9FAFB",
            "scheduled_border": "#A54FA9",
            "scheduled_shadow": "-5px 0 0 0 #A54FA9",
            "scheduled_text": "#A54FA9",
            "sla_bg": "#F9FAFB",
            "sla_border": "#8A9A46",
            "sla_shadow": "-5px 0 0 0 #8A9A46",
            "sla_text": "#8A9A46",
        },
        "final_summary": {
            "mode": "default",
            "card_bg": "#FFFFFF",
            "card_border": "#D9D9D9",
            "card_shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
            "value_color": "#000000",
            "value_size": "30px",
            "value_weight": "700",
            "label_color": "#000000",
            "label_size": "16px",
            "label_weight": "400",
            "icon_size": "36px",
            "icon_gradient_start": "#5059BC",
            "icon_gradient_end": "#F26DF9",
            "icon_shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
        },
    },
    "button": {
        "gradient_start": "#7928CA",
        "gradient_end": "#FF0080",
        "hover_overlay": "rgba(0, 0, 0, 0.12)",
        "focus_border": "#7928CA",
        "focus_shadow": "#E5E7EB",
        "disabled_bg": "#F3F4F6",
        "disabled_border": "#E5E7E8",
        "disabled_text": "#99A1AF",
    },
    "button_tertiary": {
        "text": "#FF0080",
        "bg": "#FFFFFF",
        "border": "#FF0080",
        "hover_text": "#D4006A",
        "hover_bg": "rgba(255, 0, 128, 0.10)",
        "hover_border": "#D4006A",
        "focus_text": "#D4006A",
        "focus_bg": "rgba(212, 0, 106, 0.10)",
        "focus_border": "#D4006A",
        "focus_shadow": "#F3F4F6",
        "disabled_text": "#D4006A",
        "disabled_bg": "rgba(199, 160, 180, 0.20)",
        "disabled_border": "#C7A0B4",
    },
    "navigation": {
        "active_color": "#FF0080",
        "active_hover_color": "#D4006A",
        "highlight_gradient_start": "#7928CA",
        "highlight_gradient_end": "#FF0080",
    },
    "dashboard": {
        "greeting_card": {
            "bg": "#F9FAFB",
            "text": "#252F40",
            "shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
            "radius": "12px",
            "title_color": None,
            "title_gradient": "linear-gradient(90deg, #7928CA 0%, #FF0080 100%)",
            "title_size": "30px",
            "title_weight": "700",
            "subtitle_color": "#000000",
            "subtitle_size": "20px",
            "subtitle_weight": "400",
        },
        "metric_cards": {
            "bg": "#FFFFFF",
            "border": "#E5E7EB",
            "shadow": "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
            "hover_shadow": "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
            "radius": "12px",
            "value_color": "#252F40",
            "value_size": "30px",
            "value_weight": "700",
            "label_color": "#8C8C8C",
            "label_size": "12px",
            "label_weight": "400",
            "label_transform": "uppercase",
            "label_tracking": "0.08em",
            "icon_mode": "text_gradient",
            "icon_container_size": "41px",
            "icon_color": "#FFFFFF",
            "icon_gradient_start": "#7928CA",
            "icon_gradient_end": "#FF0080",
            "icon_shadow": "none",
        },
        "legajo_states_chart": {
            "abiertos": "#08B8CC",
            "seguimiento": "#7928CA",
            "derivados": "#FF0080",
            "cerrados": "#6B7280",
        },
        "trend_line_color": "#FF0080",
        "trend_period_tabs": {
            "active_bg": "#FF0080",
            "active_text": "#FFFFFF",
            "inactive_bg": "#F3F4F6",
            "inactive_text": "#4B5563",
        },
        "activity_timeline": {
            "icon_mode": "by_type",
            "icon_bg": "",
            "icon_color": "",
            "icon_size": "0.875rem",
        },
        "quick_action_cards": {
            "icon_mode": "by_card",
            "icon_bg": "",
            "icon_color": "",
            "icon_size": "1.25rem",
        },
        "system_status": {
            "icon_mode": "by_card",
            "icon_container_bg": "",
            "icon_container_size": "4rem",
            "icon_size": "1.5rem",
            "icon_gradient_start": "",
            "icon_gradient_end": "",
            "bar_fill": "",
        },
    },
    "colors": {
        "nodo_magenta": "#FF0080",
        "nodo_purple": "#7928CA",
        "nodo_violet": "#8908CC",
        "nodo_cyan": "#08B8CC",
        "color_primario": "#7928CA",
        "color_primario_claro": "#FF0080",
        "color_primario_oscuro": "#8908CC",
        "color_secundario": "#475569",
        "color_secundario_claro": "#64748B",
        "color_secundario_oscuro": "#334155",
        "color_acento": "#08B8CC",
        "color_acento_claro": "#14B8A6",
        "color_acento_oscuro": "#0D9488",
        "fondo_principal": "#F8FAFC",
        "fondo_secundario": "#FFFFFF",
        "texto_primario": "#141414",
        "texto_secundario": "#252F40",
        "texto_terciario": "#4A5565",
        "texto_muted": "#8C8C8C",
        "border": "#E5E7EB",
        "gradient_start": "#7928CA",
        "gradient_end": "#FF0080",
    },
}


def _deep_merge(base, overrides):
    merged = copy.deepcopy(base)
    for key, value in overrides.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


BRANDING_PROFILES = {
    "default": DEFAULT_BRANDING,
    "chaco": {
        "application_name": "NODO Chaco",
        "favicon_path": "custom/branding/chaco/favicon.png",
        "sidebar_logo_path": "custom/branding/chaco/app-logo.png",
        "sidebar_collapsed_logo_path": "custom/branding/chaco/mini-logo.png",
        "login_logo_path": "custom/branding/chaco/login-logo.png",
        "login_illustration_path": "custom/branding/chaco/login-illustration.svg",
        "login_background_image_path": "custom/branding/chaco/login-background.png",
        "footer_logo_path": "custom/branding/chaco/footer-logo.png",
        "chatbot_bubble": {
            "size": "56px",
            "background": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "hover_background": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "icon_size": "1.25rem",
            "icon_color": "#FFFFFF",
        },
        "chatbot_window": {
            "header_background": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "submit_background": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "submit_hover_background": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "input_focus_ring": "#5059BC",
            "title": "Asistente Virtual",
            "welcome_message": "¡Hola! Soy tu asistente virtual. ¿En que puedo ayudarte?",
        },
        "citizen_list": {
            "action_view_color": "#F26DF9",
            "action_view_hover_bg": "#FDF4FF",
        },
        "portal": {
            "title": "Portal Ñandé",
            "subtitle": "Registro de Instituciones",
            "contact_email": "info@chaco.gob.ar",
            "logo_path": "custom/branding/chaco/mini-logo.png",
            "logo_width": "64px",
            "logo_height": "64px",
            "background_color": "#FFFFFF",
            "icon_bg": "transparent",
            "icon_name": "fa-network-wired",
            "footer_title": "Ñandé",
            "header_contact_icon_bg": "#F0F2FF",
            "header_contact_icon_border": "#C7D2FE",
            "header_contact_icon_color": "#5059BC",
            "page_header_icon_mode": "gradient",
            "page_header_icon_color": "#5059BC",
            "page_header_icon_gradient_start": "#5059BC",
            "page_header_icon_gradient_end": "#F26DF9",
            "primary_button_gradient_start": "#5059BC",
            "primary_button_gradient_end": "#F26DF9",
            "primary_button_hover_start": "#454DA8",
            "primary_button_hover_end": "#DB5FE2",
            "secondary_button_bg": "#FFFFFF",
            "secondary_button_hover_bg": "#DEE1FF",
            "secondary_button_text": "#5059BC",
            "secondary_button_border": "#5059BC",
            "floating_help_bg": "linear-gradient(180deg, #5059BC 0%, #F26DF9 100%)",
            "floating_help_hover_bg": "linear-gradient(180deg, #454DA8 0%, #DB5FE2 100%)",
            "floating_help_icon_color": "#FFFFFF",
            "stats_icon_1_bg": "#5059BC",
            "stats_icon_2_bg": "#8A9A46",
            "stats_icon_3_bg": "#F26DF9",
            "stats_icon_4_bg": "#5059BC",
            "stats_system_icon_color": "#5059BC",
            "stats_progress_1": "#8A9A46",
            "stats_progress_2": "#5059BC",
            "stats_progress_3": "#F26DF9",
            "home": {
                "status_badge_bg": "#F5F3FF",
                "status_badge_border": "#C7D2FE",
                "status_badge_text": "#5059BC",
                "status_badge_dot": "#8A9A46",
                "primary_icon_mode": "text_gradient",
                "primary_icon_gradient_start": "#5059BC",
                "primary_icon_gradient_end": "#F26DF9",
                "primary_button_gradient_start": "#5059BC",
                "primary_button_gradient_end": "#F26DF9",
                "primary_button_hover_start": "#454DA8",
                "primary_button_hover_end": "#DB5FE2",
                "secondary_icon_mode": "text_gradient",
                "secondary_icon_gradient_start": "#5059BC",
                "secondary_icon_gradient_end": "#F26DF9",
                "secondary_button_gradient_start": "#5059BC",
                "secondary_button_gradient_end": "#F26DF9",
                "secondary_button_hover_start": "#454DA8",
                "secondary_button_hover_end": "#DB5FE2",
                "tertiary_icon_mode": "text_gradient",
                "tertiary_icon_gradient_start": "#5059BC",
                "tertiary_icon_gradient_end": "#F26DF9",
                "tertiary_button_gradient_start": "#5059BC",
                "tertiary_button_gradient_end": "#F26DF9",
                "tertiary_button_hover_start": "#454DA8",
                "tertiary_button_hover_end": "#DB5FE2",
                "support_icon_mode": "text_gradient",
                "support_icon_bg": "transparent",
                "support_icon_border": "transparent",
                "support_icon_color": "#5059BC",
                "support_icon_gradient_start": "#5059BC",
                "support_icon_gradient_end": "#F26DF9",
                "support_button_bg": "linear-gradient(90deg, #5059BC 0%, #F26DF9 100%)",
                "support_button_hover_bg": "linear-gradient(90deg, #454DA8 0%, #DB5FE2 100%)",
                "contact_icon_color": "#5059BC",
                "process_title_icon_bg": "#5059BC",
                "docs_icon_bg": "#5059BC",
                "docs_check_bg": "#8A9A46",
                "steps_icon_bg": "#5059BC",
                "steps_complete_bg": "#8A9A46",
                "notice_bg": "#F5F3FF",
                "notice_border": "#C7D2FE",
                "notice_text": "#5059BC",
            },
        },
        "conversations": {
            "list": {
                "metrics_button_bg": "linear-gradient(90deg, #5059BC 0%, #F26DF9 100%)",
                "metrics_button_hover_bg": "linear-gradient(90deg, #454DA8 0%, #DB5FE2 100%)",
                "config_button_bg": "#5059BC",
                "config_button_hover_bg": "#454DA8",
                "auto_assign_button_bg": "#F26DF9",
                "auto_assign_button_hover_bg": "#DB5FE2",
                "filter_button_bg": "linear-gradient(90deg, #5059BC 0%, #F26DF9 100%)",
                "filter_button_hover_bg": "linear-gradient(90deg, #454DA8 0%, #DB5FE2 100%)",
                "stat_alert_bg": "#FDF4FF",
                "stat_alert_icon": "#F26DF9",
                "stat_success_bg": "#F7F8EE",
                "stat_success_icon": "#8A9A46",
                "stat_time_bg": "#EEF2FF",
                "stat_time_icon": "#5059BC",
                "action_view_color": "#5059BC",
                "action_view_hover_color": "#454DA8",
                "action_reassign_color": "#F26DF9",
                "action_reassign_hover_color": "#DB5FE2",
                "action_assign_color": "#8A9A46",
                "action_assign_hover_color": "#6F7B38",
            },
            "chat_public": {
                "header_icon_gradient_start": "#5059BC",
                "header_icon_gradient_end": "#F26DF9",
                "status_badge_bg": "#F5F3FF",
                "status_badge_border": "#C7D2FE",
                "status_badge_text": "#5059BC",
                "status_badge_dot": "#8A9A46",
                "secure_icon_bg": "#F0F2FF",
                "secure_icon_border": "#C7D2FE",
                "secure_icon_color": "#5059BC",
                "anonymous_icon_mode": "text_gradient",
                "anonymous_icon_gradient_start": "#5059BC",
                "anonymous_icon_gradient_end": "#F26DF9",
                "personal_icon_mode": "text_gradient",
                "personal_icon_gradient_start": "#5059BC",
                "personal_icon_gradient_end": "#F26DF9",
                "primary_button_gradient_start": "#5059BC",
                "primary_button_gradient_end": "#F26DF9",
                "primary_button_hover_start": "#454DA8",
                "primary_button_hover_end": "#DB5FE2",
                "secondary_button_gradient_start": "#5059BC",
                "secondary_button_gradient_end": "#F26DF9",
                "secondary_button_hover_start": "#454DA8",
                "secondary_button_hover_end": "#DB5FE2",
            },
        },
        "citizen_form": {
            "header_icon_mode": "gradient",
            "header_icon_bg": "transparent",
            "header_icon_color": "#FFFFFF",
            "header_icon_gradient_start": "#5059BC",
            "header_icon_gradient_end": "#F26DF9",
            "confirm_header_icon_name": "fa-user-plus",
            "confirm_header_icon_mode": "gradient",
            "confirm_header_icon_wrapper": "none",
            "confirm_header_icon_bg": "transparent",
            "confirm_header_icon_color": "#FFFFFF",
            "confirm_header_icon_gradient_start": "#5059BC",
            "confirm_header_icon_gradient_end": "#F26DF9",
            "confirm_header_icon_size": "1.5rem",
            "confirm_breadcrumb_home_icon_mode": "gradient",
            "confirm_breadcrumb_home_icon_color": "#F26DF9",
            "confirm_breadcrumb_home_icon_gradient_start": "#5059BC",
            "confirm_breadcrumb_home_icon_gradient_end": "#F26DF9",
            "confirm_renaper_card_bg": "#F5F5F5",
            "confirm_renaper_card_border": "#576784",
            "confirm_renaper_card_text": "#576784",
            "confirm_renaper_card_muted_text": "#576784",
            "confirm_renaper_card_info_bg": "#F5F5F5",
            "confirm_renaper_card_info_text": "#576784",
            "confirm_back_button_class": "btn-nodo btn-secondary btn-base",
            "renaper_header_icon_mode": "gradient",
            "renaper_header_icon_wrapper": "none",
            "renaper_header_icon_bg": "transparent",
            "renaper_header_icon_color": "#FFFFFF",
            "renaper_header_icon_gradient_start": "#5059BC",
            "renaper_header_icon_gradient_end": "#F26DF9",
            "renaper_header_icon_size": "1.5rem",
            "cancel_button_class": "btn-nodo btn-secondary btn-base",
            "back_button_class": "btn-nodo btn-secondary btn-base",
        },
        "program_detail_nachec": {
            "tab_active_border_color": "#A54FA9",
            "tab_active_text_color": "#A54FA9",
            "hero_stats": {
                "card_mode": "flat",
                "show_badges": False,
                "icon_mode": "gradient_text",
            },
            "flow_cycle": {
                "icon_mode": "gradient_badge",
            },
            "prestations_status": {
                "mode": "flat",
            },
            "final_summary": {
                "mode": "flat",
            },
        },
        "colors": {
            "nodo_magenta": "#F26DF9",
            "nodo_purple": "#5059BC",
            "nodo_violet": "#00203A",
            "nodo_cyan": "#C8D29C",
            "color_primario": "#00203A",
            "color_primario_claro": "#5059BC",
            "color_primario_oscuro": "#00203A",
            "color_secundario": "#5059BC",
            "color_secundario_claro": "#C8D29C",
            "color_secundario_oscuro": "#00203A",
            "color_acento": "#F26DF9",
            "color_acento_claro": "#C8D29C",
            "color_acento_oscuro": "#8A9A46",
            "texto_primario": "#00203A",
            "texto_secundario": "#00203A",
            "texto_terciario": "#5059BC",
            "texto_muted": "#8C8C8C",
            "border": "#C8D29C",
            "gradient_start": "#5059BC",
            "gradient_end": "#F26DF9",
        },
        "button": {
            "gradient_start": "#5059BC",
            "gradient_end": "#F26DF9",
            "hover_overlay": "rgba(0, 0, 0, 0.20)",
            "focus_border": "#5059BC",
            "focus_shadow": "#E5E7EB",
            "disabled_bg": "#F3F4F6",
            "disabled_border": "#E5E7E8",
            "disabled_text": "#99A1AF",
        },
        "button_tertiary": {
            "text": "#5059BC",
            "bg": "#FFFFFF",
            "border": "#5059BC",
            "hover_text": "#5059BC",
            "hover_bg": "#DEE1FF",
            "hover_border": "#5059BC",
            "focus_text": "#2331C9",
            "focus_bg": "#DEE1FF",
            "focus_border": "#2331C9",
            "focus_shadow": "#F3F4F6",
            "disabled_text": "#5059BC",
            "disabled_bg": "#F0F2FF",
            "disabled_border": "#5059BC",
        },
        "navigation": {
            "active_color": "#A54FA9",
            "active_hover_color": "#8C3E90",
            "highlight_gradient_start": "#5059BC",
            "highlight_gradient_end": "#A54FA9",
        },
        "dashboard": {
            "greeting_card": {
                "bg": "#F9FAFB",
                "text": "#101828",
                "shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
                "radius": "12px",
                "title_color": "#101828",
                "title_gradient": None,
                "title_size": "30px",
                "title_weight": "700",
                "subtitle_color": "#101828",
                "subtitle_size": "20px",
                "subtitle_weight": "400",
            },
            "metric_cards": {
                "bg": "#FFFFFF",
                "border": "#D9D9D9",
                "shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.10)",
                "hover_shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.10)",
                "radius": "12px",
                "value_color": "#000000",
                "value_size": "30px",
                "value_weight": "700",
                "label_color": "#000000",
                "label_size": "16px",
                "label_weight": "400",
                "label_transform": "none",
                "label_tracking": "normal",
                "icon_mode": "text_gradient",
                "icon_container_size": "41px",
                "icon_color": "#FFFFFF",
                "icon_gradient_start": "#5059BC",
                "icon_gradient_end": "#F26DF9",
                "icon_shadow": "0 4px 8px 0 rgba(0, 0, 0, 0.10)",
            },
            "legajo_states_chart": {
                "abiertos": "#C8D29C",
                "seguimiento": "#5059BC",
                "derivados": "#F26DF9",
                "cerrados": "#8A9A46",
            },
            "trend_line_color": "#5059BC",
            "trend_period_tabs": {
                "active_bg": "#5059BC",
                "active_text": "#FFFFFF",
                "inactive_bg": "#F3F4F6",
                "inactive_text": "#4B5563",
            },
            "activity_timeline": {
                "icon_mode": "uniform",
                "icon_bg": "#B5BAF0",
                "icon_color": "#5059BC",
                "icon_size": "19px",
            },
            "quick_action_cards": {
                "icon_mode": "uniform",
                "icon_bg": "",
                "icon_color": "#5059BC",
                "icon_size": "25px",
            },
            "system_status": {
                "icon_mode": "uniform_gradient",
                "icon_container_bg": "#E5E7EB",
                "icon_container_size": "41px",
                "icon_size": "25px",
                "icon_gradient_start": "#5059BC",
                "icon_gradient_end": "#F26DF9",
                "bar_fill": "linear-gradient(45deg, #5059BC 0%, #F26DF9 100%)",
            },
        },
    },
}


def _build_css_variables(branding):
    colors = branding["colors"]
    button = branding["button"]
    button_tertiary = branding["button_tertiary"]
    navigation = branding["navigation"]
    gradient = f"linear-gradient(45deg, {colors['gradient_start']} 0%, {colors['gradient_end']} 100%)"
    sidebar_gradient = (
        f"linear-gradient(135deg, {colors['color_primario']} 0%, {colors['color_primario_oscuro']} 100%)"
    )
    button_gradient = f"linear-gradient(45deg, {button['gradient_start']} 0%, {button['gradient_end']} 100%)"
    highlight_gradient = (
        f"linear-gradient(90deg, {navigation['highlight_gradient_start']} 0%, {navigation['highlight_gradient_end']} 100%)"
    )

    return {
        "--color-primario": colors["color_primario"],
        "--color-primario-claro": colors["color_primario_claro"],
        "--color-primario-oscuro": colors["color_primario_oscuro"],
        "--color-secundario": colors["color_secundario"],
        "--color-secundario-claro": colors["color_secundario_claro"],
        "--color-secundario-oscuro": colors["color_secundario_oscuro"],
        "--color-acento": colors["color_acento"],
        "--color-acento-claro": colors["color_acento_claro"],
        "--color-acento-oscuro": colors["color_acento_oscuro"],
        "--fondo-principal": colors["fondo_principal"],
        "--fondo-secundario": colors["fondo_secundario"],
        "--fondo-sidebar": sidebar_gradient,
        "--texto-primario": colors["texto_primario"],
        "--texto-secundario": colors["texto_secundario"],
        "--nodo-magenta": colors["nodo_magenta"],
        "--nodo-purple": colors["nodo_purple"],
        "--nodo-violet": colors["nodo_violet"],
        "--nodo-cyan": colors["nodo_cyan"],
        "--nodo-text-primary": colors["texto_primario"],
        "--nodo-text-secondary": colors["texto_secundario"],
        "--nodo-text-tertiary": colors["texto_terciario"],
        "--nodo-text-muted": colors["texto_muted"],
        "--nodo-border": colors["border"],
        "--nodo-bg-white": colors["fondo_secundario"],
        "--nodo-gradient": gradient,
        "--login-button-gradient": button_gradient,
        "--login-button-hover-overlay": button["hover_overlay"],
        "--login-button-focus-border": button["focus_border"],
        "--login-button-focus-shadow": button["focus_shadow"],
        "--login-button-disabled-bg": button["disabled_bg"],
        "--login-button-disabled-border": button["disabled_border"],
        "--login-button-disabled-text": button["disabled_text"],
        "--button-tertiary-text": button_tertiary["text"],
        "--button-tertiary-bg": button_tertiary["bg"],
        "--button-tertiary-border": button_tertiary["border"],
        "--button-tertiary-hover-text": button_tertiary["hover_text"],
        "--button-tertiary-hover-bg": button_tertiary["hover_bg"],
        "--button-tertiary-hover-border": button_tertiary["hover_border"],
        "--button-tertiary-focus-text": button_tertiary["focus_text"],
        "--button-tertiary-focus-bg": button_tertiary["focus_bg"],
        "--button-tertiary-focus-border": button_tertiary["focus_border"],
        "--button-tertiary-focus-shadow": button_tertiary["focus_shadow"],
        "--button-tertiary-disabled-text": button_tertiary["disabled_text"],
        "--button-tertiary-disabled-bg": button_tertiary["disabled_bg"],
        "--button-tertiary-disabled-border": button_tertiary["disabled_border"],
        "--nav-active-color": navigation["active_color"],
        "--nav-active-hover-color": navigation["active_hover_color"],
        "--ui-highlight-color": navigation["active_color"],
        "--ui-highlight-gradient": highlight_gradient,
    }


def get_branding_profile():
    profile_key = os.environ.get("APP_PRESENTATION", "default").strip().lower() or "default"
    active_key = profile_key if profile_key in BRANDING_PROFILES else "default"
    profile_overrides = BRANDING_PROFILES[active_key]
    branding = _deep_merge(DEFAULT_BRANDING, profile_overrides)
    branding["active_profile"] = active_key
    branding["css_variables"] = _build_css_variables(branding)
    return branding
