# Generated by Django 4.2.20 on 2026-06-19 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0034_ciudadano_campos_perfil_ampliado'),
        ('flujos', '0003_tareaflujo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Ej: Evaluador, Coordinador territorial, Aprobador', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_flujo', to='legajos.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Rol de programa',
                'verbose_name_plural': 'Roles de programa',
                'ordering': ['programa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRolPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_rol_programa_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='flujos.rolprograma', verbose_name='Rol de programa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_programa_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de rol de programa',
                'verbose_name_plural': 'Asignaciones de rol de programa',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='rolprograma',
            constraint=models.UniqueConstraint(fields=('programa', 'nombre'), name='uq_rolprograma_programa_nombre'),
        ),
        migrations.AddIndex(
            model_name='asignacionrolprograma',
            index=models.Index(fields=['usuario', 'rol'], name='ix_asignrol_usuario_rol'),
        ),
        migrations.AddConstraint(
            model_name='asignacionrolprograma',
            constraint=models.UniqueConstraint(fields=('rol', 'usuario'), name='uq_asignrolprograma_rol_usuario'),
        ),
    ]
