# Generated by Django 4.2.20 on 2026-02-26 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='el squad mas picante', max_length=180)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('RUNNING', 'En ejecución'), ('PAUSED', 'Pausado'), ('FAILED', 'Fallido'), ('SUCCEEDED', 'Exitoso'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=20)),
                ('scope', models.CharField(blank=True, default='', max_length=120)),
                ('need_title', models.CharField(max_length=240)),
                ('need_description', models.TextField()),
                ('language', models.CharField(default='es', max_length=16)),
                ('mode_interactive', models.BooleanField(default=True)),
                ('max_iterations', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=32)),
                ('context_pack_versions', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_squad_run',
            },
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALISTA_FUNCIONAL', 'Analista Funcional'), ('ARQUITECTO_SW', 'Arquitecto de Software'), ('ANALISTA_DB', 'Analista de Base de Datos'), ('UX_UI', 'UX/UI'), ('DEV_BACKEND', 'Dev Backend'), ('DEV_FRONT', 'Dev Front'), ('QA', 'QA')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('WAITING_USER', 'Esperando usuario'), ('FAILED', 'Fallido'), ('SUCCEEDED', 'Exitoso'), ('SKIPPED', 'Omitido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_squad.squadrun')),
            ],
            options={
                'db_table': 'ai_squad_step',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSquadRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='el squad mas picante', max_length=180)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('RUNNING', 'En ejecución'), ('PAUSED', 'Pausado'), ('FAILED', 'Fallido'), ('SUCCEEDED', 'Exitoso'), ('CANCELED', 'Cancelado')], default='CREATED', max_length=20)),
                ('scope', models.CharField(blank=True, default='', max_length=120)),
                ('need_title', models.CharField(max_length=240)),
                ('need_description', models.TextField()),
                ('language', models.CharField(default='es', max_length=16)),
                ('mode_interactive', models.BooleanField(default=True)),
                ('max_iterations', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=32)),
                ('context_pack_versions', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical squad run',
                'verbose_name_plural': 'historical squad runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRunStep',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALISTA_FUNCIONAL', 'Analista Funcional'), ('ARQUITECTO_SW', 'Arquitecto de Software'), ('ANALISTA_DB', 'Analista de Base de Datos'), ('UX_UI', 'UX/UI'), ('DEV_BACKEND', 'Dev Backend'), ('DEV_FRONT', 'Dev Front'), ('QA', 'QA')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('WAITING_USER', 'Esperando usuario'), ('FAILED', 'Fallido'), ('SUCCEEDED', 'Exitoso'), ('SKIPPED', 'Omitido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_squad.squadrun')),
            ],
            options={
                'verbose_name': 'historical run step',
                'verbose_name_plural': 'historical run steps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGateResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gate_type', models.CharField(choices=[('LINT', 'Lint/Format'), ('TESTS', 'Tests'), ('SECURITY', 'Checklist Seguridad'), ('PERFORMANCE', 'Chequeo Performance'), ('BRAND', 'Manual de Marca (UX/UI)')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('PASSED', 'Aprobado'), ('FAILED', 'Rechazado'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.TextField(blank=True, default='')),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_squad.squadrun')),
                ('step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_squad.runstep')),
            ],
            options={
                'verbose_name': 'historical gate result',
                'verbose_name_plural': 'historical gate results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArtifact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('RF', 'Requerimiento Funcional'), ('ARCH', 'Diseño/Arquitectura'), ('DB', 'Diseño Base de Datos'), ('UX', 'UX/UI'), ('CODE_BACKEND', 'Código Backend'), ('CODE_FRONT', 'Código Front/Mobile'), ('TESTS', 'Tests'), ('QA_REPORT', 'Reporte QA'), ('PR_PACKAGE', 'Paquete PR'), ('LOG', 'Log/Notas')], max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_text', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_squad.squadrun')),
                ('step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai_squad.runstep')),
            ],
            options={
                'verbose_name': 'historical artifact',
                'verbose_name_plural': 'historical artifacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_type', models.CharField(choices=[('LINT', 'Lint/Format'), ('TESTS', 'Tests'), ('SECURITY', 'Checklist Seguridad'), ('PERFORMANCE', 'Chequeo Performance'), ('BRAND', 'Manual de Marca (UX/UI)')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('PASSED', 'Aprobado'), ('FAILED', 'Rechazado'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.TextField(blank=True, default='')),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='ai_squad.squadrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='ai_squad.runstep')),
            ],
            options={
                'db_table': 'ai_squad_gate_result',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RF', 'Requerimiento Funcional'), ('ARCH', 'Diseño/Arquitectura'), ('DB', 'Diseño Base de Datos'), ('UX', 'UX/UI'), ('CODE_BACKEND', 'Código Backend'), ('CODE_FRONT', 'Código Front/Mobile'), ('TESTS', 'Tests'), ('QA_REPORT', 'Reporte QA'), ('PR_PACKAGE', 'Paquete PR'), ('LOG', 'Log/Notas')], max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_text', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai_squad.squadrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='ai_squad.runstep')),
            ],
            options={
                'db_table': 'ai_squad_artifact',
            },
        ),
        migrations.AddIndex(
            model_name='squadrun',
            index=models.Index(fields=['status'], name='ai_squad_ru_status_5295b0_idx'),
        ),
        migrations.AddIndex(
            model_name='squadrun',
            index=models.Index(fields=['scope'], name='ai_squad_ru_scope_b1f673_idx'),
        ),
        migrations.AddIndex(
            model_name='squadrun',
            index=models.Index(fields=['created_by'], name='ai_squad_ru_created_670304_idx'),
        ),
        migrations.AddIndex(
            model_name='squadrun',
            index=models.Index(fields=['-id'], name='ai_squad_ru_id_165a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['run', 'order'], name='ai_squad_st_run_id_1d4ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['run', 'role'], name='ai_squad_st_run_id_7803c1_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['status'], name='ai_squad_st_status_da4017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runstep',
            unique_together={('run', 'order')},
        ),
        migrations.AddIndex(
            model_name='gateresult',
            index=models.Index(fields=['run', 'gate_type'], name='ai_squad_ga_run_id_15ffe2_idx'),
        ),
        migrations.AddIndex(
            model_name='gateresult',
            index=models.Index(fields=['status'], name='ai_squad_ga_status_324ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['run', 'type'], name='ai_squad_ar_run_id_aaabd2_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['run', 'created_at'], name='ai_squad_ar_run_id_dfaf68_idx'),
        ),
    ]
