# Generated by Django 4.2.20 on 2026-02-19 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anonima', 'Anónima'), ('personal', 'Personal')], db_index=True, max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], db_index=True, default='pendiente', max_length=10)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=10)),
                ('dni_ciudadano', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('sexo_ciudadano', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_asignacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tiempo_espera_segundos', models.IntegerField(default=0)),
                ('tiempo_respuesta_segundos', models.IntegerField(blank=True, db_index=True, null=True)),
                ('satisfaccion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, null=True)),
                ('operador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ColaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('max_conversaciones', models.IntegerField(default=5)),
                ('conversaciones_actuales', models.IntegerField(db_index=True, default=0)),
                ('ultima_asignacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('peso_asignacion', models.IntegerField(default=1)),
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cola_asignacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['conversaciones_actuales', 'ultima_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='NuevaConversacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversaciones.conversacion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['operador', 'vista'], name='conversacio_operado_3a0895_idx'), models.Index(fields=['conversacion', 'vista'], name='conversacio_convers_5927c1_idx')],
                'unique_together': {('conversacion', 'operador')},
            },
        ),
        migrations.CreateModel(
            name='MetricasOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversaciones_atendidas', models.IntegerField(default=0)),
                ('tiempo_respuesta_promedio', models.FloatField(default=0.0)),
                ('satisfaccion_promedio', models.FloatField(default=0.0)),
                ('conversaciones_cerradas', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Métricas de Operadores',
                'indexes': [models.Index(fields=['operador'], name='conversacio_operado_9b70a5_idx'), models.Index(fields=['fecha_actualizacion'], name='conversacio_fecha_a_2bd3f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('operador', 'Operador')], db_index=True, max_length=10)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('leido', models.BooleanField(db_index=True, default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='conversaciones.conversacion')),
            ],
            options={
                'ordering': ['fecha_envio'],
                'indexes': [models.Index(fields=['conversacion', 'fecha_envio'], name='conversacio_convers_36806d_idx'), models.Index(fields=['remitente', 'leido'], name='conversacio_remiten_17239a_idx'), models.Index(fields=['conversacion', 'leido'], name='conversacio_convers_4a506b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='conversaciones.conversacion')),
                ('operador_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_anteriores', to=settings.AUTH_USER_MODEL)),
                ('operador_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_nuevas', to=settings.AUTH_USER_MODEL)),
                ('usuario_que_asigna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['conversacion', '-fecha_asignacion'], name='conversacio_convers_e53dde_idx'), models.Index(fields=['operador_nuevo', '-fecha_asignacion'], name='conversacio_operado_29ebc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialAlertaConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_CONVERSACION', 'Nueva Conversación'), ('NUEVO_MENSAJE', 'Nuevo Mensaje'), ('RIESGO_CRITICO', 'Riesgo Crítico')], max_length=20)),
                ('mensaje', models.CharField(max_length=200)),
                ('vista', models.BooleanField(default=False)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversaciones.conversacion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['operador', 'vista', '-creado'], name='conversacio_operado_fe96be_idx'), models.Index(fields=['conversacion', 'tipo'], name='conversacio_convers_3e0cca_idx'), models.Index(fields=['tipo', 'vista'], name='conversacio_tipo_ce9dc2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['estado', 'prioridad'], name='conversacio_estado_e7234d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['operador_asignado', 'estado'], name='conversacio_operado_4501e2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_inicio'], name='conversacio_fecha_i_adffb0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['tipo', 'estado'], name='conversacio_tipo_c9c2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['dni_ciudadano'], name='conversacio_dni_ciu_ae4058_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['satisfaccion'], name='conversacio_satisfa_c55d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_cierre'], name='conversacio_fecha_c_c9573f_idx'),
        ),
        migrations.AddIndex(
            model_name='colaasignacion',
            index=models.Index(fields=['activo', 'conversaciones_actuales'], name='conversacio_activo_bcbccd_idx'),
        ),
        migrations.AddIndex(
            model_name='colaasignacion',
            index=models.Index(fields=['operador', 'activo'], name='conversacio_operado_8810fd_idx'),
        ),
    ]
