const BRANDING_PROFILES = {
  default: {
    applicationName: 'NODO',
    loginSubtitle: 'Inicia sesion para continuar',
    registerSubtitle: 'Unete a NODO',
    assets: {
      logo: require('../../assets/brand/logo-nodo.png'),
      miniLogo: require('../../assets/brand/logo-nodo.png'),
      bannerBackground: require('../../assets/images/back_banner.jpg'),
    },
    banner: {
      mode: 'image',
      color: '#FF0080',
    },
    colors: {
      primary: '#FF0080',
      secondary: '#7928CA',
      accent: '#08B8CC',
      success: '#2DCE89',
      warning: '#FFB020',
      text: '#252F40',
      textMuted: '#67748E',
      textSoft: '#8392AB',
      border: '#E9ECEF',
      background: '#F8F9FA',
      surface: '#FFFFFF',
      darkBackground: '#101828',
      darkSurface: '#1C293A',
      darkSurfaceAlt: '#252F40',
      darkText: '#FFFFFF',
      darkTextMuted: '#E5E7EB',
      darkTextSoft: '#8C8C8C',
      darkBorder: '#4A5565',
      icon: '#56606A',
      buttonSecondaryText: '#4A5565',
      buttonSecondaryBg: '#F9FAFB',
      buttonSecondaryBorder: '#E5E7EB',
      buttonSecondaryHoverBg: '#F3F4F6',
      buttonTertiaryText: '#FF0080',
      buttonTertiaryBg: '#FFFFFF',
      buttonTertiaryBorder: '#FF0080',
      buttonTertiaryHoverText: '#D4006A',
      buttonTertiaryHoverBg: 'rgba(255, 0, 128, 0.10)',
      buttonTertiaryHoverBorder: '#D4006A',
      buttonTertiaryFocusText: '#D4006A',
      buttonTertiaryFocusBg: 'rgba(212, 0, 106, 0.10)',
      buttonTertiaryFocusBorder: '#D4006A',
      buttonDisabledBg: '#F3F4F6',
      buttonDisabledBorder: '#E5E7E8',
      buttonDisabledText: '#99A1AF',
      authGlow: '#FF0080',
      authNetworkLine: 'rgba(180, 32, 176, 0.35)',
      authNodeOuter: 'rgba(255, 0, 128, 0.18)',
      authNodeInner: 'rgba(255, 0, 128, 0.9)',
      authGrid: 'rgba(255, 0, 128, 0.07)',
      authBlobA: 'rgba(255, 0, 128, 0.18)',
      authBlobB: 'rgba(121, 40, 202, 0.16)',
      authBlobC: 'rgba(137, 8, 204, 0.14)',
    },
    gradients: {
      brand: ['#FF0080', '#7928CA'],
      buttonPrimary: ['#7828CA', '#FF0080'],
      buttonPrimaryPressedOverlay: 'rgba(0, 0, 0, 0.20)',
    },
  },
  chaco: {
    applicationName: 'NODO Chaco',
    loginSubtitle: 'Inicia sesion para continuar',
    registerSubtitle: 'Unete a Nande',
    assets: {
      logo: require('../../assets/brand/logo-chaco.png'),
      miniLogo: require('../../assets/brand/mini-logo-chaco.png'),
      bannerBackground: require('../../assets/images/back_banner.jpg'),
    },
    banner: {
      mode: 'solid',
      color: '#5059BC',
    },
    colors: {
      primary: '#5059BC',
      secondary: '#F26DF9',
      accent: '#C8D29C',
      success: '#8A9A46',
      warning: '#F26DF9',
      text: '#101828',
      textMuted: '#8C8C8C',
      textSoft: '#576784',
      border: '#D9D9D9',
      background: '#F8F9FA',
      surface: '#FFFFFF',
      darkBackground: '#101828',
      darkSurface: '#1C293A',
      darkSurfaceAlt: '#252F40',
      darkText: '#FFFFFF',
      darkTextMuted: '#E5E7EB',
      darkTextSoft: '#8C8C8C',
      darkBorder: '#4A5565',
      icon: '#5059BC',
      buttonSecondaryText: '#5059BC',
      buttonSecondaryBg: '#F9FAFB',
      buttonSecondaryBorder: '#D9D9D9',
      buttonSecondaryHoverBg: '#F0F2FF',
      buttonTertiaryText: '#5059BC',
      buttonTertiaryBg: '#FFFFFF',
      buttonTertiaryBorder: '#5059BC',
      buttonTertiaryHoverText: '#5059BC',
      buttonTertiaryHoverBg: '#DEE1FF',
      buttonTertiaryHoverBorder: '#5059BC',
      buttonTertiaryFocusText: '#2331C9',
      buttonTertiaryFocusBg: '#DEE1FF',
      buttonTertiaryFocusBorder: '#2331C9',
      buttonDisabledBg: '#F3F4F6',
      buttonDisabledBorder: '#E5E7E8',
      buttonDisabledText: '#99A1AF',
      authGlow: '#5059BC',
      authNetworkLine: 'rgba(80, 89, 188, 0.35)',
      authNodeOuter: 'rgba(80, 89, 188, 0.20)',
      authNodeInner: 'rgba(242, 109, 249, 0.95)',
      authGrid: 'rgba(80, 89, 188, 0.08)',
      authBlobA: 'rgba(80, 89, 188, 0.16)',
      authBlobB: 'rgba(242, 109, 249, 0.14)',
      authBlobC: 'rgba(138, 154, 70, 0.14)',
    },
    gradients: {
      brand: ['#5059BC', '#F26DF9'],
      buttonPrimary: ['#5059BC', '#F26DF9'],
      buttonPrimaryPressedOverlay: 'rgba(0, 0, 0, 0.20)',
    },
  },
};

const ACTIVE_PROFILE = process.env.EXPO_PUBLIC_APP_PRESENTATION || 'chaco';

export const activeBranding = BRANDING_PROFILES[ACTIVE_PROFILE] || BRANDING_PROFILES.default;
export const activeBrandProfile = BRANDING_PROFILES[ACTIVE_PROFILE] ? ACTIVE_PROFILE : 'default';
export { BRANDING_PROFILES };
