# Generated by Django 4.2.20 on 2026-04-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDinamicoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('codigo', models.CharField(db_index=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('seleccion', 'Seleccion'), ('email', 'Email'), ('telefono', 'Telefono'), ('dni', 'DNI'), ('archivo', 'Archivo')], default='texto', max_length=20)),
                ('obligatorio', models.BooleanField(db_index=True, default=False)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('placeholder', models.CharField(blank=True, max_length=120)),
                ('ayuda', models.CharField(blank=True, max_length=255)),
                ('valor_default', models.CharField(blank=True, max_length=255)),
                ('longitud_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_dinamicos', to='reclamos.tiporeclamo')),
            ],
            options={
                'verbose_name': 'Campo dinamico de reclamo',
                'verbose_name_plural': 'Campos dinamicos de reclamo',
                'ordering': ['tipo_reclamo', 'orden', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampoDinamicoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('valor', models.CharField(max_length=120)),
                ('etiqueta', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='reclamos.campodinamicoreclamo')),
            ],
            options={
                'verbose_name': 'Opcion de campo dinamico',
                'verbose_name_plural': 'Opciones de campo dinamico',
                'ordering': ['campo', 'orden', 'etiqueta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReclamoDatoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('valor', models.JSONField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_cargados', to='reclamos.campodinamicoreclamo')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_dinamicos', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Dato dinamico de reclamo',
                'verbose_name_plural': 'Datos dinamicos de reclamo',
                'ordering': ['reclamo', 'campo__orden', 'id'],
                'indexes': [models.Index(fields=['reclamo', 'campo'], name='reclamos_re_reclamo_50068d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reclamodatodinamico',
            constraint=models.UniqueConstraint(fields=('reclamo', 'campo'), name='reclamos_dato_reclamo_campo_uk'),
        ),
        migrations.AddConstraint(
            model_name='campodinamicoreclamo',
            constraint=models.UniqueConstraint(fields=('tipo_reclamo', 'codigo'), name='reclamos_campo_tipo_codigo_uk'),
        ),
        migrations.AddConstraint(
            model_name='campodinamicoopcion',
            constraint=models.UniqueConstraint(fields=('campo', 'valor'), name='reclamos_campo_opcion_valor_uk'),
        ),
    ]
