# Generated by Django 4.2.20 on 2026-04-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reclamos', '0002_campodinamicoreclamo_campodinamicoopcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReclamoTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('requiere_comentario', models.BooleanField(default=False)),
                ('requiere_asignado', models.BooleanField(default=False)),
                ('requiere_area_responsable', models.BooleanField(default=False)),
                ('estado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrada', to='reclamos.estadoreclamo')),
                ('estado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salida', to='reclamos.estadoreclamo')),
                ('areas_permitidas', models.ManyToManyField(blank=True, related_name='transiciones_estado_reclamo', to='reclamos.area')),
                ('grupos_permitidos', models.ManyToManyField(blank=True, related_name='transiciones_estado_reclamo', to='auth.group')),
            ],
            options={
                'verbose_name': 'Transicion de estado de reclamo',
                'verbose_name_plural': 'Transiciones de estado de reclamo',
                'ordering': ['estado_origen', 'orden', 'id'],
                'indexes': [models.Index(fields=['estado_origen', 'activo'], name='reclamos_es_estado__92f6a9_idx'), models.Index(fields=['estado_destino', 'activo'], name='reclamos_es_estado__f1b047_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='estadoreclamotransicion',
            constraint=models.UniqueConstraint(fields=('estado_origen', 'estado_destino'), name='reclamos_estado_transicion_origen_destino_uk'),
        ),
    ]
