# Generated by Django 4.2.20 on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reclamos", "0003_estadoreclamotransicion"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subareas",
                to="reclamos.area",
            ),
        ),
    ]
