# Generated by Django 4.2.20 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamos", "0004_area_parent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="area",
            name="reclamos_area_codigo_municipio_uk",
        ),
        migrations.RemoveConstraint(
            model_name="prioridadreclamo",
            name="reclamos_prioridad_codigo_municipio_uk",
        ),
        migrations.RemoveConstraint(
            model_name="estadoreclamo",
            name="reclamos_estado_codigo_municipio_uk",
        ),
        migrations.RemoveConstraint(
            model_name="tiporeclamo",
            name="reclamos_tipo_nombre_municipio_uk",
        ),
        migrations.RemoveField(
            model_name="area",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="estadoreclamo",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="prioridadreclamo",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="tiporeclamo",
            name="municipio",
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(fields=("codigo",), name="reclamos_area_codigo_uk"),
        ),
        migrations.AddConstraint(
            model_name="prioridadreclamo",
            constraint=models.UniqueConstraint(fields=("codigo",), name="reclamos_prioridad_codigo_uk"),
        ),
        migrations.AddConstraint(
            model_name="estadoreclamo",
            constraint=models.UniqueConstraint(fields=("codigo",), name="reclamos_estado_codigo_uk"),
        ),
        migrations.AddConstraint(
            model_name="tiporeclamo",
            constraint=models.UniqueConstraint(fields=("nombre",), name="reclamos_tipo_nombre_uk"),
        ),
    ]
