# Generated by Django 4.2.20 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamos", "0005_remove_municipio_catalogos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiporeclamo",
            name="imagen_portada",
            field=models.ImageField(blank=True, null=True, upload_to="reclamos/tipos/portadas/%Y/%m/"),
        ),
    ]
