# Generated by Django 4.2.20 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reclamos", "0006_tiporeclamo_imagen_portada"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiporeclamo",
            name="destacado",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
