from .views_actividades import (
    ActividadDetailView,
    ActividadEditarView,
    DerivacionAceptarView,
    DerivacionRechazarView,
    InscriptoEditarView,
    StaffActividadCreateView,
    buscar_personal_ajax,
)
from .views_extra import (
    AsistenciaView,
    StaffDesasignarView,
    StaffEditarView,
    TomarAsistenciaView,
)
from .views_geografia import (
    LocalidadCreateView,
    LocalidadDeleteView,
    LocalidadListView,
    LocalidadUpdateView,
    MunicipioCreateView,
    MunicipioDeleteView,
    MunicipioListView,
    MunicipioUpdateView,
    ProvinciaCreateView,
    ProvinciaDeleteView,
    ProvinciaListView,
    ProvinciaUpdateView,
)
from .views_institucional import (
    DispositivoCreateView,
    DispositivoForm,
    DispositivoListView,
    DispositivoRed,
    DispositivoUpdateView,
    EvaluacionInstitucionCreateView,
    IndicadorInstitucionCreateView,
    InstitucionCreateView,
    InstitucionDeleteView,
    InstitucionDetailView,
    InstitucionListView,
    InstitucionUpdateView,
    PersonalInstitucionCreateView,
    PlanFortalecimientoCreateView,
    documento_subir,
)
