# Generated by Django 4.2.20 on 2025-10-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajoatencion',
            options={'verbose_name': 'Acompañamiento', 'verbose_name_plural': 'Acompañamientos'},
        ),
    ]
