# Generated by Django 4.2.20 on 2025-11-02 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sesionusuario_logdescargaarchivo_logaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0002_alter_legajoatencion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegajoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('OBSERVACION', 'En Observación'), ('SUSPENDIDO', 'Suspendido'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=20)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('institucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legajo_institucional', to='core.institucion')),
                ('responsable_sedronar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legajos_institucionales_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legajo Institucional',
                'verbose_name_plural': 'Legajos Institucionales',
            },
        ),
        migrations.CreateModel(
            name='PlanFortalecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('objetivos', models.TextField()),
                ('actividades', models.JSONField(help_text='Lista de actividades planificadas')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
                ('legajo_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_fortalecimiento', to='legajos.legajoinstitucional')),
                ('responsable_seguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Fortalecimiento',
                'verbose_name_plural': 'Planes de Fortalecimiento',
            },
        ),
        migrations.CreateModel(
            name='PersonalInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('DIRECTOR', 'Director/a'), ('COORDINADOR', 'Coordinador/a'), ('PROFESIONAL', 'Profesional'), ('OPERADOR', 'Operador/a'), ('ADMINISTRATIVO', 'Administrativo/a'), ('OTRO', 'Otro')], max_length=20)),
                ('titulo_profesional', models.CharField(blank=True, max_length=200)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('legajo_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='legajos.legajoinstitucional')),
            ],
            options={
                'verbose_name': 'Personal de Institución',
                'verbose_name_plural': 'Personal de Instituciones',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_evaluacion', models.DateField()),
                ('infraestructura', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Puntuación 1-10')),
                ('recursos_humanos', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Puntuación 1-10')),
                ('programas_servicios', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Puntuación 1-10')),
                ('gestion_administrativa', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Puntuación 1-10')),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legajo_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='legajos.legajoinstitucional')),
            ],
            options={
                'verbose_name': 'Evaluación Institucional',
                'verbose_name_plural': 'Evaluaciones Institucionales',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre_capacitacion', models.CharField(max_length=200)),
                ('institucion_capacitadora', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas_catedra', models.PositiveIntegerField(blank=True, null=True)),
                ('certificado', models.FileField(blank=True, upload_to='capacitaciones/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='legajos.personalinstitucion')),
            ],
            options={
                'verbose_name': 'Capacitación de Personal',
                'verbose_name_plural': 'Capacitaciones de Personal',
            },
        ),
        migrations.CreateModel(
            name='IndicadorInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(help_text='Ej: 2024-01, 2024-Q1', max_length=20)),
                ('beneficiarios_atendidos', models.PositiveIntegerField(default=0)),
                ('derivaciones_recibidas', models.PositiveIntegerField(default=0)),
                ('derivaciones_enviadas', models.PositiveIntegerField(default=0)),
                ('servicios_brindados', models.JSONField(blank=True, help_text='Lista de servicios y cantidades', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('legajo_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='legajos.legajoinstitucional')),
            ],
            options={
                'verbose_name': 'Indicador Institucional',
                'verbose_name_plural': 'Indicadores Institucionales',
                'unique_together': {('legajo_institucional', 'periodo')},
            },
        ),
    ]
