# Generated by Django 4.2.20 on 2025-11-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0003_legajoinstitucional_planfortalecimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfortalecimiento',
            options={'verbose_name': 'Actividad Institucional', 'verbose_name_plural': 'Actividades Institucionales'},
        ),
        migrations.RemoveField(
            model_name='planfortalecimiento',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='planfortalecimiento',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='planfortalecimiento',
            name='responsable_seguimiento',
        ),
        migrations.RemoveField(
            model_name='planfortalecimiento',
            name='vigente',
        ),
        migrations.AddField(
            model_name='planfortalecimiento',
            name='cupo_ciudadanos',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima de ciudadanos'),
        ),
        migrations.AddField(
            model_name='planfortalecimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planfortalecimiento',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='planfortalecimiento',
            name='subtipo',
            field=models.CharField(choices=[('PREVENCION_UNIVERSAL', 'Prevención Universal'), ('PREVENCION_SELECTIVA', 'Prevención Selectiva'), ('PREVENCION_INDICADA', 'Prevención Indicada'), ('AMBULATORIO', 'Ambulatorio'), ('INTERNACION', 'Internación'), ('HOSPITAL_DIA', 'Hospital de Día'), ('INTERCAMBIO_JERINGAS', 'Intercambio de Jeringas'), ('TESTEO_VIH', 'Testeo VIH'), ('CONSEJERIA', 'Consejería'), ('LABORAL', 'Laboral'), ('EDUCATIVA', 'Educativa'), ('SOCIAL', 'Social'), ('PROFESIONAL', 'Profesional'), ('OPERADORES', 'Operadores'), ('COMUNIDAD', 'Comunidad')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planfortalecimiento',
            name='tipo',
            field=models.CharField(choices=[('PREVENCION', 'Prevención'), ('TRATAMIENTO', 'Tratamiento'), ('REDUCCION_RIESGO', 'Reducción de Riesgo'), ('REINSERCION', 'Reinserción Social'), ('CAPACITACION', 'Capacitación'), ('OTRO', 'Otro')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planfortalecimiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StaffActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('rol_en_actividad', models.CharField(help_text='Ej: Coordinador, Terapeuta, Operador', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='legajos.planfortalecimiento')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.personalinstitucion')),
            ],
            options={
                'verbose_name': 'Staff de Actividad',
                'verbose_name_plural': 'Staff de Actividades',
                'unique_together': {('actividad', 'personal')},
            },
        ),
    ]
