# Generated by Django 4.2.20 on 2025-11-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ABANDONADO', 'Abandonado')], default='INSCRITO', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='legajos.planfortalecimiento')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_inscrito', to='legajos.ciudadano')),
            ],
            options={
                'verbose_name': 'Inscripto en Actividad',
                'verbose_name_plural': 'Inscriptos en Actividades',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('actividad', 'ciudadano')},
            },
        ),
        migrations.AddField(
            model_name='derivacion',
            name='actividad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='legajos.planfortalecimiento', verbose_name='Actividad Específica'),
        ),
        migrations.CreateModel(
            name='HistorialStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('DESASIGNACION', 'Desasignación'), ('CAMBIO_ROL', 'Cambio de Rol')], max_length=20)),
                ('descripcion', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='legajos.staffactividad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Staff',
                'verbose_name_plural': 'Historiales de Staff',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInscripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('ACTIVACION', 'Activación'), ('FINALIZACION', 'Finalización'), ('ABANDONO', 'Abandono')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='legajos.inscriptoactividad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Inscripto',
                'verbose_name_plural': 'Historiales de Inscriptos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ACEPTACION', 'Aceptación'), ('RECHAZO', 'Rechazo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='legajos.derivacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Derivación',
                'verbose_name_plural': 'Historiales de Derivaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('SUSPENSION', 'Suspensión'), ('FINALIZACION', 'Finalización'), ('REACTIVACION', 'Reactivación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='legajos.planfortalecimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historiales de Actividades',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AlertaAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('AUSENTISMO_3', '3 días consecutivos'), ('AUSENTISMO_5', '5 días consecutivos'), ('AUSENTISMO_SEMANAL', 'Más del 50% semanal')], max_length=20)),
                ('dias_ausente', models.PositiveIntegerField()),
                ('fecha_inicio_ausencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ausentismo', to='legajos.inscriptoactividad')),
                ('vista_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_ausentismo_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Ausentismo',
                'verbose_name_plural': 'Alertas de Ausentismo',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Ausente Justificado'), ('TARDANZA', 'Tardanza')], max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='legajos.inscriptoactividad')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha'],
                'unique_together': {('inscripto', 'fecha')},
            },
        ),
    ]
