# Generated by Django 4.2.20 on 2025-11-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0009_inscriptoactividad_derivacion_actividad_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinstitucion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_institucion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalinstitucion',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
