# Generated by Django 4.2.20 on 2025-11-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0010_add_partitioning_indexes'),
        ('legajos', '0010_personalinstitucion_usuario_and_more'),
    ]

    operations = [
    ]
