# Generated by Django 4.2.20 on 2025-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0011_merge_20251105_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaciudadano',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='alertaciudadano',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertaciudadano',
            name='prioridad',
            field=models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alertaciudadano',
            name='tipo',
            field=models.CharField(choices=[('RIESGO_ALTO', 'Riesgo Alto'), ('RIESGO_SUICIDA', 'Riesgo Suicida'), ('VIOLENCIA', 'Situación de Violencia'), ('SIN_CONTACTO', 'Sin Contacto Prolongado'), ('SIN_EVALUACION', 'Sin Evaluación Inicial'), ('SIN_PLAN', 'Sin Plan de Intervención'), ('EVENTO_CRITICO', 'Evento Crítico Reciente'), ('DERIVACION_PENDIENTE', 'Derivación Pendiente'), ('SIN_RED_FAMILIAR', 'Sin Red Familiar'), ('SIN_CONSENTIMIENTO', 'Sin Consentimiento'), ('CONTACTOS_FALLIDOS', 'Contactos Fallidos'), ('PLAN_VENCIDO', 'Plan Vencido')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='nombre',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='fecha_aceptacion',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='urgencia',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], db_index=True, default='MEDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacioninicial',
            name='riesgo_suicida',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si presenta riesgo suicida', verbose_name='Riesgo Suicida'),
        ),
        migrations.AlterField(
            model_name='evaluacioninicial',
            name='violencia',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si presenta situación de violencia', verbose_name='Situación de Violencia'),
        ),
        migrations.AlterField(
            model_name='eventocritico',
            name='tipo',
            field=models.CharField(choices=[('SOBREDOSIS', 'Sobredosis'), ('CRISIS', 'Crisis aguda'), ('VIOLENCIA', 'Violencia'), ('INTERNACION', 'Internación')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='legajoatencion',
            name='fecha_admision',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='legajoatencion',
            name='nivel_riesgo',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], db_index=True, default='BAJO', max_length=20),
        ),
        migrations.AlterField(
            model_name='legajoatencion',
            name='plan_vigente',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='legajoatencion',
            name='via_ingreso',
            field=models.CharField(choices=[('ESPONTANEA', 'Consulta espontánea'), ('DERIVACION', 'Derivación'), ('JUDICIAL', 'Judicial'), ('HOSPITAL', 'Hospital/Guardia')], db_index=True, default='ESPONTANEA', max_length=20),
        ),
        migrations.AlterField(
            model_name='planintervencion',
            name='vigente',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='seguimientocontacto',
            name='adherencia',
            field=models.CharField(blank=True, choices=[('ADECUADA', 'Adecuada'), ('PARCIAL', 'Parcial'), ('NULA', 'Nula')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimientocontacto',
            name='tipo',
            field=models.CharField(choices=[('ENTREVISTA', 'Entrevista'), ('VISITA', 'Visita'), ('LLAMADA', 'Llamada'), ('TALLER', 'Taller')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='alertaciudadano',
            index=models.Index(fields=['activa', 'prioridad', '-creado'], name='legajos_ale_activa_6b8b11_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaciudadano',
            index=models.Index(fields=['cerrada_por', 'fecha_cierre'], name='legajos_ale_cerrada_e42828_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['activo', 'apellido'], name='legajos_ciu_activo_b779fe_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['email'], name='legajos_ciu_email_e7552c_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacion',
            index=models.Index(fields=['estado', 'urgencia'], name='legajos_der_estado_20d638_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacion',
            index=models.Index(fields=['destino', 'estado'], name='legajos_der_destino_7b4005_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacion',
            index=models.Index(fields=['origen', 'estado'], name='legajos_der_origen__6fcc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['plan_vigente', 'estado'], name='legajos_leg_plan_vi_489fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['via_ingreso', 'fecha_admision'], name='legajos_leg_via_ing_a35e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['dispositivo', 'estado'], name='legajos_leg_disposi_397712_idx'),
        ),
        migrations.AddIndex(
            model_name='planintervencion',
            index=models.Index(fields=['profesional', 'vigente'], name='legajos_pla_profesi_0cbb48_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientocontacto',
            index=models.Index(fields=['adherencia', 'legajo'], name='legajos_seg_adheren_644e29_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientocontacto',
            index=models.Index(fields=['profesional', '-creado'], name='legajos_seg_profesi_a62371_idx'),
        ),
    ]
