# Generated by Django 4.2.20 on 2025-11-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_institucion_activo_alter_institucion_email_and_more'),
        ('legajos', '0012_alter_alertaciudadano_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajoatencion',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legajos', to='core.institucion', verbose_name='Institución'),
        ),
    ]
