# Generated by Django 4.2.20 on 2025-11-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0013_alter_legajoatencion_dispositivo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='derivacion',
            name='legajos_der_origen__6fcc9a_idx',
        ),
        migrations.RemoveField(
            model_name='derivacion',
            name='origen',
        ),
    ]
