# Generated by Django 4.2.20 on 2026-02-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0014_remove_derivacion_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ACOMPANAMIENTO_SEDRONAR', 'Acompañamiento SEDRONAR'), ('NACHEC', 'ÑACHEC'), ('ECONOMICO', 'Acompañamiento Económico'), ('FAMILIAR', 'Acompañamiento Familiar')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', help_text='Color hex para la UI', max_length=20)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono', max_length=50)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('requiere_evaluacion', models.BooleanField(default=True)),
                ('requiere_plan', models.BooleanField(default=True)),
                ('requiere_seguimientos', models.BooleanField(default=True)),
                ('modelo_legajo', models.CharField(blank=True, help_text='Nombre del modelo de legajo (ej: LegajoAtencion, LegajoNachec)', max_length=100)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('EN_SEGUIMIENTO', 'En Seguimiento'), ('SUSPENDIDO', 'Suspendido'), ('CERRADO', 'Cerrado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('via_ingreso', models.CharField(choices=[('DIRECTO', 'Ingreso Directo'), ('DERIVACION_INTERNA', 'Derivación Interna'), ('DERIVACION_EXTERNA', 'Derivación Externa'), ('ESPONTANEO', 'Espontáneo')], default='DIRECTO', max_length=30)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, db_index=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, db_index=True, null=True)),
                ('legajo_id', models.UUIDField(blank=True, help_text='ID del legajo específico del programa', null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_programas', to='legajos.ciudadano')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='legajos.programa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a Programa',
                'verbose_name_plural': 'Inscripciones a Programas',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='DerivacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField()),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], db_index=True, default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_programas', to='legajos.ciudadano')),
                ('derivado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_programas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('inscripcion_creada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacion_origen', to='legajos.inscripcionprograma')),
                ('inscripcion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_realizadas', to='legajos.inscripcionprograma')),
                ('programa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_destino', to='legajos.programa')),
                ('programa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_origen', to='legajos.programa')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_programas_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación entre Programas',
                'verbose_name_plural': 'Derivaciones entre Programas',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['ciudadano', 'estado'], name='legajos_ins_ciudada_c9810b_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['programa', 'estado'], name='legajos_ins_program_73dc01_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionprograma',
            index=models.Index(fields=['estado', 'fecha_inscripcion'], name='legajos_ins_estado_e7ff4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together={('ciudadano', 'programa')},
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['ciudadano', 'estado'], name='legajos_der_ciudada_3ad38b_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['programa_destino', 'estado'], name='legajos_der_program_ac3470_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacionprograma',
            index=models.Index(fields=['estado', 'urgencia'], name='legajos_der_estado_6f16db_idx'),
        ),
    ]
