# Generated by Django 4.2.20 on 2026-02-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_auditoriaciudadano_ciudadano'),
        ('legajos', '0015_programa_inscripcionprograma_derivacionprograma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del caso (para reaperturas)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_SEGUIMIENTO', 'En Seguimiento'), ('SUSPENDIDO', 'Suspendido'), ('EGRESADO', 'Egresado'), ('CERRADO', 'Cerrado')], db_index=True, default='ACTIVO', max_length=20)),
                ('es_caso_activo', models.BooleanField(db_index=True, default=True, help_text='True si estado es ACTIVO o EN_SEGUIMIENTO')),
                ('fecha_apertura', models.DateField(auto_now_add=True, db_index=True)),
                ('fecha_cierre', models.DateField(blank=True, db_index=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_institucionales', to='legajos.ciudadano')),
            ],
            options={
                'verbose_name': 'Caso Institucional',
                'verbose_name_plural': 'Casos Institucionales',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.RemoveField(
            model_name='legajoinstitucional',
            name='estado',
        ),
        migrations.AddField(
            model_name='legajoinstitucional',
            name='estado_global',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('OBSERVACION', 'En Observación'), ('SUSPENDIDO', 'Suspendido'), ('CERRADO', 'Cerrado')], db_index=True, default='ACTIVO', help_text='Si es CERRADO, bloquea todos los programas de la institución', max_length=20, verbose_name='Estado Global'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Color hex para la UI (ej: #6366f1)', max_length=20),
        ),
        migrations.AlterField(
            model_name='programa',
            name='icono',
            field=models.CharField(default='folder', help_text='Nombre del ícono (ej: people, assessment, school)', max_length=50),
        ),
        migrations.AlterField(
            model_name='programa',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización en solapas (menor = primero)'),
        ),
        migrations.CreateModel(
            name='InstitucionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_programa', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CERRADO', 'Cerrado')], db_index=True, default='ACTIVO', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si False, no se muestra solapa en UI')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, help_text='Capacidad máxima de casos simultáneos', null=True)),
                ('controlar_cupo', models.BooleanField(default=False, help_text='Si True, valida cupo al aceptar derivaciones')),
                ('permite_sobrecupo', models.BooleanField(default=False, help_text='Si True, permite aceptar derivaciones con cupo lleno')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_habilitados', to='core.institucion')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_habilitadas', to='legajos.programa')),
                ('responsable_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institucion_programas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institución-Programa',
                'verbose_name_plural': 'Instituciones-Programas',
            },
        ),
        migrations.CreateModel(
            name='IndicadorProgramatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('periodo', models.DateField(db_index=True, help_text='Primer día del mes del período')),
                ('total_casos', models.PositiveIntegerField(default=0)),
                ('total_derivaciones', models.PositiveIntegerField(default=0)),
                ('cupo_utilizado', models.PositiveIntegerField(default=0)),
                ('casos_activos', models.PositiveIntegerField(default=0)),
                ('casos_egresados', models.PositiveIntegerField(default=0)),
                ('derivaciones_aceptadas', models.PositiveIntegerField(default=0)),
                ('derivaciones_rechazadas', models.PositiveIntegerField(default=0)),
                ('institucion_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='legajos.institucionprograma')),
            ],
            options={
                'verbose_name': 'Indicador Programático',
                'verbose_name_plural': 'Indicadores Programáticos',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='legajos.casoinstitucional')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Caso',
                'verbose_name_plural': 'Historiales de Estados de Casos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='DerivacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('ACEPTADA_UNIFICADA', 'Aceptada Unificada')], db_index=True, default='PENDIENTE', max_length=25)),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], db_index=True, default='MEDIA', max_length=10)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('caso_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacion_creadora', to='legajos.casoinstitucional')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_institucionales', to='legajos.ciudadano')),
                ('derivado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_institucionales_realizadas', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_recibidas', to='core.institucion')),
                ('institucion_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones', to='legajos.institucionprograma')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_programa', to='legajos.programa')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_institucionales_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación Institucional',
                'verbose_name_plural': 'Derivaciones Institucionales',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='casoinstitucional',
            name='derivacion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caso_generado', to='legajos.derivacioninstitucional'),
        ),
        migrations.AddField(
            model_name='casoinstitucional',
            name='institucion_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='legajos.institucionprograma'),
        ),
        migrations.AddField(
            model_name='casoinstitucional',
            name='responsable_caso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_institucionales_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsuarioInstitucionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('RESPONSABLE_LOCAL', 'Responsable Local'), ('COORDINADOR', 'Coordinador'), ('OPERADOR', 'Operador'), ('STAFF', 'Staff')], default='OPERADOR', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('institucion_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='legajos.institucionprograma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_programas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Programa',
                'verbose_name_plural': 'Usuarios-Programas',
                'indexes': [models.Index(fields=['usuario', 'activo'], name='legajos_usu_usuario_a620fe_idx'), models.Index(fields=['institucion_programa', 'rol'], name='legajos_usu_institu_d5e82c_idx')],
                'unique_together': {('usuario', 'institucion_programa')},
            },
        ),
        migrations.AddIndex(
            model_name='institucionprograma',
            index=models.Index(fields=['institucion', 'activo'], name='legajos_ins_institu_5440c0_idx'),
        ),
        migrations.AddIndex(
            model_name='institucionprograma',
            index=models.Index(fields=['programa', 'estado_programa'], name='legajos_ins_program_d4bb01_idx'),
        ),
        migrations.AddIndex(
            model_name='institucionprograma',
            index=models.Index(fields=['estado_programa', 'activo'], name='legajos_ins_estado__44df8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institucionprograma',
            unique_together={('institucion', 'programa')},
        ),
        migrations.AddIndex(
            model_name='indicadorprogramatico',
            index=models.Index(fields=['institucion_programa', '-periodo'], name='legajos_ind_institu_e9777e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicadorprogramatico',
            unique_together={('institucion_programa', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='historialestadocaso',
            index=models.Index(fields=['caso', '-creado'], name='legajos_his_caso_id_9326ba_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacioninstitucional',
            index=models.Index(fields=['ciudadano', 'estado'], name='legajos_der_ciudada_823ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacioninstitucional',
            index=models.Index(fields=['institucion_programa', 'estado'], name='legajos_der_institu_df6ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacioninstitucional',
            index=models.Index(fields=['estado', 'urgencia'], name='legajos_der_estado_6c8a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='derivacioninstitucional',
            index=models.Index(fields=['institucion', 'programa'], name='legajos_der_institu_601383_idx'),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['ciudadano', 'estado'], name='legajos_cas_ciudada_f96148_idx'),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['institucion_programa', 'estado'], name='legajos_cas_institu_747f58_idx'),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['estado', 'es_caso_activo'], name='legajos_cas_estado_9dd986_idx'),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['responsable_caso', 'estado'], name='legajos_cas_respons_837703_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casoinstitucional',
            unique_together={('ciudadano', 'institucion_programa', 'es_caso_activo')},
        ),
    ]
