# Generated by Django 4.2.20 on 2026-02-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0016_casoinstitucional_remove_legajoinstitucional_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(help_text='Identificador técnico (ej: ACOMPANAMIENTO_SEDRONAR)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='folder', help_text="Nombre del ícono FontAwesome (sin 'fa-')", max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Color hexadecimal para UI', max_length=7)),
                ('orden', models.PositiveIntegerField(default=100, help_text='Orden de aparición en solapas')),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='historialestadocaso',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='historialestadocaso',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='indicadorprogramatico',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indicadorprogramatico',
            name='institucion_programa',
        ),
        migrations.AlterUniqueTogether(
            name='usuarioinstitucionprograma',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuarioinstitucionprograma',
            name='institucion_programa',
        ),
        migrations.RemoveField(
            model_name='usuarioinstitucionprograma',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='casoinstitucional',
            options={'verbose_name': 'Caso Institucional', 'verbose_name_plural': 'Casos Institucionales'},
        ),
        migrations.RemoveIndex(
            model_name='casoinstitucional',
            name='legajos_cas_estado_9dd986_idx',
        ),
        migrations.RemoveIndex(
            model_name='casoinstitucional',
            name='legajos_cas_respons_837703_idx',
        ),
        migrations.AlterUniqueTogether(
            name='casoinstitucional',
            unique_together={('ciudadano', 'institucion_programa', 'version')},
        ),
        migrations.AddField(
            model_name='casoinstitucional',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casoinstitucional',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_institucionales_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casoinstitucional',
            name='codigo',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='legajos_cas_estado_5fbb60_idx'),
        ),
        migrations.AddIndex(
            model_name='casoinstitucional',
            index=models.Index(fields=['responsable', 'estado'], name='legajos_cas_respons_b45afe_idx'),
        ),
        migrations.DeleteModel(
            name='HistorialEstadoCaso',
        ),
        migrations.DeleteModel(
            name='IndicadorProgramatico',
        ),
        migrations.DeleteModel(
            name='UsuarioInstitucionPrograma',
        ),
        migrations.RemoveField(
            model_name='casoinstitucional',
            name='derivacion_origen',
        ),
        migrations.RemoveField(
            model_name='casoinstitucional',
            name='es_caso_activo',
        ),
        migrations.RemoveField(
            model_name='casoinstitucional',
            name='motivo_cierre',
        ),
        migrations.RemoveField(
            model_name='casoinstitucional',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='casoinstitucional',
            name='responsable_caso',
        ),
        migrations.AlterField(
            model_name='derivacioninstitucional',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_programa', to='legajos.programainstitucional'),
        ),
        migrations.AlterField(
            model_name='institucionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_habilitadas', to='legajos.programainstitucional'),
        ),
    ]
