# Generated by Django 4.2.20 on 2026-02-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0017_programainstitucional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si False, el usuario pierde acceso al programa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinadores', to='legajos.programainstitucional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_coordinados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinador de Programa',
                'verbose_name_plural': 'Coordinadores de Programas',
                'indexes': [models.Index(fields=['usuario', 'activo'], name='legajos_coo_usuario_c3dedb_idx'), models.Index(fields=['programa', 'activo'], name='legajos_coo_program_13967c_idx')],
                'unique_together': {('usuario', 'programa')},
            },
        ),
    ]
