# Generated by Django 4.2.20 on 2026-03-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0032_inscriptoactividad_codigo_inscripto_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('TARDANZA', 'Tardanza')], db_index=True, default='AUSENTE', max_length=12, verbose_name='Estado de asistencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Asistencia a clase',
                'verbose_name_plural': 'Asistencias a clases',
                'ordering': ['clase__fecha', 'clase__hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ClaseActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('duracion_minutos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duración (minutos)')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Clase de actividad',
                'verbose_name_plural': 'Clases de actividad',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.RenameIndex(
            model_name='derivacionciudadano',
            new_name='legajos_der_ciudada_90a6bb_idx',
            old_name='der_ciu_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='derivacionciudadano',
            new_name='legajos_der_institu_0fba3d_idx',
            old_name='der_ip_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='derivacionciudadano',
            new_name='legajos_der_estado_dd4589_idx',
            old_name='der_estado_urgencia_idx',
        ),
        migrations.RenameIndex(
            model_name='derivacionciudadano',
            new_name='legajos_der_institu_fc1d09_idx',
            old_name='der_inst_prog_idx',
        ),
        migrations.RenameIndex(
            model_name='programa',
            new_name='legajos_pro_estado_e23362_idx',
            old_name='legajos_pro_estado_orden_idx',
        ),
        migrations.AlterField(
            model_name='inscriptoactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='legajos.planfortalecimiento', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='inscriptoactividad',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_inscrito', to='legajos.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Color hex para la UI (ej: #6366f1)', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='icono',
            field=models.CharField(default='folder', help_text='Nombre del ícono (ej: people, assessment, school)', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización en solapas (menor = primero)', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='claseactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='legajos.planfortalecimiento', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='claseactividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='legajos.claseactividad', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_clase', to='legajos.inscriptoactividad', verbose_name='Inscripción'),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_clase_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='claseactividad',
            index=models.Index(fields=['actividad', 'fecha'], name='idx_claseact_actividad_fecha'),
        ),
        migrations.AddConstraint(
            model_name='claseactividad',
            constraint=models.UniqueConstraint(fields=('actividad', 'fecha', 'hora_inicio'), name='unique_clase_actividad_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='asistenciaclase',
            index=models.Index(fields=['clase', 'estado'], name='idx_asistclass_clase_estado'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.UniqueConstraint(fields=('clase', 'inscripcion'), name='unique_asistencia_clase_inscripcion'),
        ),
    ]
