# Generated by Django 4.2.20 on 2026-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0033_claseactividad_asistenciaclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='cobertura_medica',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cobertura médica'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='condiciones_vivienda',
            field=models.TextField(blank=True, verbose_name='Condiciones de la vivienda'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='dni_fisico',
            field=models.CharField(blank=True, choices=[('TIENE', 'Tiene DNI'), ('EN_TRAMITE', 'En trámite'), ('NO_TIENE', 'No tiene')], max_length=15, verbose_name='DNI físico'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='estado_migratorio',
            field=models.CharField(blank=True, choices=[('NACIONAL', 'Nacional'), ('RESIDENTE_PERMANENTE', 'Residente permanente'), ('RESIDENTE_TEMPORARIO', 'Residente temporario'), ('SOLICITANTE_ASILO', 'Solicitante de asilo'), ('IRREGULAR', 'Situación irregular')], max_length=25, verbose_name='Estado migratorio'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='estado_renaper',
            field=models.CharField(blank=True, choices=[('REGISTRADO', 'Registrado'), ('NO_REGISTRADO', 'No registrado'), ('CON_OBSERVACION', 'Con observación'), ('FALLECIDO', 'Fallecido')], max_length=20, verbose_name='Estado RENAPER'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ciudadanos/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ingreso_estimado',
            field=models.CharField(blank=True, choices=[('SIN_INGRESO', 'Sin ingreso'), ('MENOS_CBT', 'Menos de una CBT'), ('ENTRE_1_2_CBT', 'Entre 1 y 2 CBT'), ('MAS_2_CBT', 'Más de 2 CBT')], max_length=20, verbose_name='Ingreso estimado'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='medicacion_habitual',
            field=models.TextField(blank=True, verbose_name='Medicación habitual'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('SIN_INSTRUCCION', 'Sin instrucción'), ('PRIMARIO_INCOMPLETO', 'Primario incompleto'), ('PRIMARIO_COMPLETO', 'Primario completo'), ('SECUNDARIO_INCOMPLETO', 'Secundario incompleto'), ('SECUNDARIO_COMPLETO', 'Secundario completo'), ('TERCIARIO', 'Terciario / universitario'), ('POSGRADO', 'Posgrado')], max_length=25, verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='obra_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Obra social / prepaga'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='situacion_laboral',
            field=models.CharField(blank=True, choices=[('EMPLEADO_FORMAL', 'Empleado formal'), ('EMPLEADO_INFORMAL', 'Empleado informal'), ('CUENTAPROPISTA', 'Cuenta propia'), ('DESEMPLEADO', 'Desempleado'), ('JUBILADO', 'Jubilado / pensionado'), ('ESTUDIANTE', 'Estudiante'), ('SIN_ACTIVIDAD', 'Sin actividad'), ('OTRO', 'Otro')], max_length=20, verbose_name='Situación laboral'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='tenencia_vivienda',
            field=models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge / conviviente'), ('FAMILIAR', 'Familiar'), ('INQUILINO', 'Inquilino'), ('OCUPANTE', 'Ocupante sin título'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tenencia de vivienda'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('ALQUILADA', 'Alquilada'), ('PRESTADA', 'Prestada / cedida'), ('VILLA', 'Villa / asentamiento'), ('SIN_TECHO', 'Sin techo'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vivienda'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['tipo_vivienda'], name='legajos_ciu_tipo_vi_838aad_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['situacion_laboral'], name='legajos_ciu_situaci_290b65_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['nivel_educativo'], name='legajos_ciu_nivel_e_b5c5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['estado_renaper'], name='legajos_ciu_estado__bec08e_idx'),
        ),
    ]
